
import { Exercise, ExerciseComponentType, OriginalIconName } from './types';

// Specific exercises for Second Grade - Numeros (s1)
export const secondGradeNumerosExercises: Exercise[] = [
  { 
    id: 'g2-s1-e1', title: 'Contar y Escribir hasta 200', 
    description: 'Practica la lectura y escritura de números hasta doscientos.', 
    iconName: 'BookOpenIcon', isLocked: false, 
    componentType: ExerciseComponentType.ESCRIBIR_HASTA_10000,
    data: { totalStars: 10, minNumber: 100, maxNumber: 200 }, // Focus on 100-200
    question: 'Escribe el número en cifras:',
  },
  { 
    id: 'g2-s1-e2', title: 'Comparar Números hasta 200', 
    description: 'Utiliza <, =, > para comparar pares de números hasta el doscientos.', 
    iconName: 'BookOpenIcon', isLocked: false, 
    componentType: ExerciseComponentType.COMPARAR_HASTA_10000,
    data: { totalStars: 10, minNumber: 0, maxNumber: 200 },
    question: 'Compara los siguientes números:',
  },
  { 
    id: 'g2-s1-e3', title: 'Valor Posicional (U, D, C)', 
    description: 'Identifica unidades, decenas y centenas en números hasta 999.', 
    iconName: 'NumbersIcon', isLocked: false, 
    componentType: ExerciseComponentType.COMPONER_HASTA_10000_TEXTO,
    data: { totalStars: 10, minNumber: 100, maxNumber: 999, placeValuesToAsk: ['c', 'd', 'u'] },
    question: 'Indica cuántas C, D y U tiene el número:',
  },
  { 
    id: 'g2-s1-e4', title: 'Componer con Ábaco (hasta 999)', 
    description: 'Representa números de tres cifras usando el ábaco interactivo.', 
    iconName: 'OwlIcon', isLocked: false, 
    componentType: ExerciseComponentType.COMPONER_HASTA_10000_ABACO,
    data: { totalStars: 8, minNumber: 100, maxNumber: 999, placeValuesToShow: ['c','d','u'] },
    question: 'Representa el número en el ábaco:',
  },
  { 
    id: 'g2-s1-e5', title: 'Descomponer Números (hasta 999)', 
    description: 'Expresa números como suma de sus centenas, decenas y unidades.', 
    iconName: 'NumbersIcon', isLocked: false, 
    componentType: ExerciseComponentType.COMPONER_HASTA_10000_TEXTO, // Reuses this component
    data: { totalStars: 10, minNumber: 100, maxNumber: 999, placeValuesToAsk: ['c', 'd', 'u'] },
    question: 'Descompón el número:',
  },
  { 
    id: 'g2-s1-e6', title: 'Escribir Números hasta 1.000', 
    description: 'Escribe en cifras los números dados en palabras hasta el mil.', 
    iconName: 'BookOpenIcon', isLocked: false, 
    componentType: ExerciseComponentType.ESCRIBIR_HASTA_10000,
    data: { totalStars: 10, minNumber: 201, maxNumber: 1000 }, // Focus on 201-1000
    question: 'Escribe el número:',
  },
  { 
    id: 'g2-s1-e7', title: 'Comparar Números hasta 1.000', 
    description: 'Utiliza los símbolos <, =, > para comparar números hasta el mil.', 
    iconName: 'BookOpenIcon', isLocked: false, 
    componentType: ExerciseComponentType.COMPARAR_HASTA_10000,
    data: { totalStars: 10, minNumber: 100, maxNumber: 1000 },
    question: 'Compara usando <, = ó >:',
  },
  { 
    id: 'g2-s1-e8', title: 'Ordenar Números (hasta 1.000)', 
    description: 'Organiza series de números de tres cifras de menor a mayor o viceversa.', 
    iconName: 'NumbersIcon', isLocked: false, 
    componentType: ExerciseComponentType.ORDENAR_NUMEROS_SIMPLE,
    data: { totalStars: 5, count: 5, numberRange: [100, 999], sortOrder: 'asc' },
    question: 'Ordena los números:',
  },
  { 
    id: 'g2-s1-e9', title: 'Anterior y Posterior (hasta 1.000)', 
    description: 'Identifica el número que va antes y después de un número dado hasta mil.', 
    iconName: 'NumbersIcon', isLocked: false, 
    componentType: ExerciseComponentType.NUMERO_ANTERIOR_POSTERIOR,
    data: { totalStars: 10, minNumber: 100, maxNumber: 999 },
    question: 'Completa el anterior y posterior:',
  },
  { 
    id: 'g2-s1-e10', title: 'Redondear a la Decena Más Cercana', 
    description: 'Aprende a aproximar números de dos y tres cifras a la decena más próxima.', 
    iconName: 'BookOpenIcon', isLocked: false, 
    componentType: ExerciseComponentType.APROXIMAR_NUMERO,
    data: { totalStars: 10, minNumber: 10, maxNumber: 999, roundingUnit: 10 },
    question: 'Redondea a la decena más cercana:',
  },
  { 
    id: 'g2-s1-e11', title: 'Números Ordinales hasta el Vigésimo (20º)', 
    description: 'Reconoce y utiliza los números ordinales del primero al vigésimo.', 
    iconName: 'BookOpenIcon', isLocked: false, 
    componentType: ExerciseComponentType.IDENTIFICAR_ORDINALES,
    data: { totalStars: 10, minCardinal: 1, maxCardinal: 20 },
    question: '¿Qué número ordinal es?',
  },
  { 
    id: 'g2-s1-e12', title: 'Pares e Impares (hasta 100)', 
    description: 'Clasifica números de hasta dos cifras como pares o impares.', 
    iconName: 'NumbersIcon', isLocked: false, 
    componentType: ExerciseComponentType.IDENTIFICAR_PARES_IMPARES,
    data: { totalStars: 10, maxNumber: 100 },
    question: '¿Es par o impar?',
  },
  { 
    id: 'g2-s1-e13a', title: 'Dobles (hasta 25)', 
    description: 'Calcula el doble de números hasta 25.', 
    iconName: 'OperationsIcon', isLocked: false, 
    componentType: ExerciseComponentType.CALCULA_MENTALMENTE,
    data: { totalStars: 5, problemType: 'double', minOperand: 1, maxOperand: 25 },
    question: 'Calcula el doble:',
  },
  { 
    id: 'g2-s1-e13b', title: 'Mitades (pares hasta 50)', 
    description: 'Calcula la mitad de números pares hasta 50.', 
    iconName: 'OperationsIcon', isLocked: false, 
    componentType: ExerciseComponentType.CALCULA_MENTALMENTE,
    data: { totalStars: 5, problemType: 'half', minOperand: 2, maxOperand: 50 },
    question: 'Calcula la mitad:',
  },
  { 
    id: 'g2-s1-e14', title: 'Introducción a la Multiplicación (Visual)', 
    description: 'Comprende la multiplicación como sumas repetidas a través de ejemplos visuales.', 
    iconName: 'OperationsIcon', isLocked: false, 
    componentType: ExerciseComponentType.VISUAL_MULTIPLICATION_INTRO, 
    data: { totalStars: 5, maxGroups: 5, maxInGroup: 5 },
    question: '¿Cuántos hay en total? (suma repetida)',
  },
  { 
    id: 'g2-s1-e15', title: 'Tablas del 2, 5 y 10 (Introducción)', 
    description: 'Comienza a familiarizarte con las tablas de multiplicar del 2, 5 y 10.', 
    iconName: 'OperationsIcon', isLocked: false, 
    componentType: ExerciseComponentType.MULTIPLICATION_TABLE_PRACTICE, 
    data: { totalStars: 10, tables: [2, 5, 10], maxMultiplier: 10 },
    question: 'Completa la tabla:',
  },
  { 
    id: 'g2-s1-e16', title: 'Fracciones: Mitades y Cuartos (Visual)', 
    description: 'Identifica y nombra mitades (1/2) y cuartos (1/4) en figuras divididas.', 
    iconName: 'BookOpenIcon', isLocked: false, 
    componentType: ExerciseComponentType.REPRESENTAR_FRACCIONES,
    data: { totalStars: 10, denominators: [2, 4], specificNumerators: { '2': [1], '4': [1,2,3] } },
    question: 'Selecciona la fracción que representa la parte coloreada:',
  },
];
