
export interface Scenario {
  id: string;
  problemTextTemplate: (num1: number, num2: number) => string;
  operation: '+' | '-' | '*' | '/'; // Updated operation types
  data1Label: string; 
  data1Unit: string;  
  data2Label: string; 
  data2Unit: string;  
  resultLabelTemplate: (result: number) => string; 
  icon: string; // Emoji
}

// Helper to generate random numbers within a range for scenarios
const getRandomInt = (min: number, max: number): number => {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

export enum ScenarioSetId {
  GENERAL = 'general_problems',
  TECHNOLOGY = 'technology_problems',
  HOUSE = 'house_problems',
  TRANSPORT = 'transport_problems',
  VIDEOGAMES = 'videogame_problems',
  FOOD = 'food_problems',
  MIXED_OPERATIONS_ADVANCED = 'mixed_operations_advanced_problems',
  FIRST_GRADE_ADD_SUB_EASY = 'first_grade_add_sub_easy', // New
  FIRST_GRADE_ADD_SUB_LT100_SIMPLE = 'first_grade_add_sub_lt100_simple', // New
}

// --- SCENARIOS FOR 1ST GRADE: Results < 10 (or simple sums up to 20) ---
const firstGradeEasyAddSubScenarios: Scenario[] = [
  // Sums
  {
    id: 'g1_globos_suma_simple',
    problemTextTemplate: (n1, n2) => `Tienes ${n1} globo${n1 === 1 ? '' : 's'}. Te regalan ${n2} más. ¿Cuántos globos tienes ahora?`,
    operation: '+', data1Label: 'Globos tenías', data1Unit: 'globos', data2Label: 'Te regalan', data2Unit: 'globos',
    resultLabelTemplate: (res) => `Ahora tienes ${res} globo${res === 1 ? '' : 's'}.`, icon: '🎈',
  },
  {
    id: 'g1_manzanas_junta_simple',
    problemTextTemplate: (n1, n2) => `Juntas ${n1} manzana${n1 === 1 ? '' : 's'} rojas y ${n2} manzana${n2 === 1 ? '' : 's'} verdes. ¿Cuántas manzanas tienes en total?`,
    operation: '+', data1Label: 'Manzanas rojas', data1Unit: 'manzanas', data2Label: 'Manzanas verdes', data2Unit: 'manzanas',
    resultLabelTemplate: (res) => `Tienes ${res} manzana${res === 1 ? '' : 's'} en total.`, icon: '🍎',
  },
  {
    id: 'g1_lapices_compra_simple',
    problemTextTemplate: (n1, n2) => `Hay ${n1} lápiz${n1 === 1 ? '' : 'ces'} en la caja. Compras ${n2} más. ¿Cuántos lápices hay ahora?`,
    operation: '+', data1Label: 'Lápices había', data1Unit: 'lápices', data2Label: 'Compras', data2Unit: 'lápices',
    resultLabelTemplate: (res) => `Ahora hay ${res} lápiz${res === 1 ? '' : 'ces'}.`, icon: '✏️',
  },
  {
    id: 'g1_autitos_amigo_simple',
    problemTextTemplate: (n1, n2) => `Tienes ${n1} autito${n1 === 1 ? '' : 's'}. Tu amigo te da ${n2}. ¿Cuántos autitos tienes en total?`,
    operation: '+', data1Label: 'Autitos tenías', data1Unit: 'autitos', data2Label: 'Te da', data2Unit: 'autitos',
    resultLabelTemplate: (res) => `Tienes ${res} autito${res === 1 ? '' : 's'} en total.`, icon: '🚗',
  },
  {
    id: 'g1_flores_recoge_simple',
    problemTextTemplate: (n1, n2) => `Recoges ${n1} flor${n1 === 1 ? '' : 'es'} amarillas y ${n2} flor${n2 === 1 ? '' : 'es'} rojas. ¿Cuántas flores recogiste?`,
    operation: '+', data1Label: 'Flores amarillas', data1Unit: 'flores', data2Label: 'Flores rojas', data2Unit: 'flores',
    resultLabelTemplate: (res) => `Recogiste ${res} flor${res === 1 ? '' : 'es'}.`, icon: '🌸',
  },
   {
    id: 'g1_peces_agrega_simple',
    problemTextTemplate: (n1, n2) => `En la pecera hay ${n1} ${n1 === 1 ? 'pez' : 'peces'}. Agregan ${n2} más. ¿Cuántos peces hay ahora?`,
    operation: '+', data1Label: 'Peces había', data1Unit: 'peces', data2Label: 'Agregan', data2Unit: 'peces',
    resultLabelTemplate: (res) => `Ahora hay ${res} ${res === 1 ? 'pez' : 'peces'}.`, icon: '🐠',
  },
  {
    id: 'g1_libros_estante_simple',
    problemTextTemplate: (n1, n2) => `Hay ${n1} ${n1 === 1 ? 'libro' : 'libros'} en un estante. Pones ${n2} más. ¿Cuántos libros hay ahora?`,
    operation: '+', data1Label: 'Libros había', data1Unit: 'libros', data2Label: 'Pones', data2Unit: 'libros',
    resultLabelTemplate: (res) => `Ahora hay ${res} ${res === 1 ? 'libro' : 'libros'}.`, icon: '📚',
  },
  {
    id: 'g1_patos_laguna_simple',
    problemTextTemplate: (n1, n2) => `Nadan ${n1} ${n1 === 1 ? 'pato' : 'patos'} en la laguna. Llegan ${n2} más. ¿Cuántos patos nadan ahora?`,
    operation: '+', data1Label: 'Patos nadando', data1Unit: 'patos', data2Label: 'Llegan', data2Unit: 'patos',
    resultLabelTemplate: (res) => `Ahora nadan ${res} ${res === 1 ? 'pato' : 'patos'}.`, icon: '🦆',
  },
  {
    id: 'g1_soles_dibuja_simple',
    problemTextTemplate: (n1, n2) => `Dibujas ${n1} ${n1 === 1 ? 'sol' : 'soles'} pequeños. Luego dibujas ${n2} más. ¿Cuántos soles dibujaste?`,
    operation: '+', data1Label: 'Soles dibujados', data1Unit: 'soles', data2Label: 'Dibuja más', data2Unit: 'soles',
    resultLabelTemplate: (res) => `Dibujaste ${res} ${res === 1 ? 'sol' : 'soles'}.`, icon: '☀️',
  },
   {
    id: 'g1_nubes_cielo_simple',
    problemTextTemplate: (n1, n2) => `Ves ${n1} ${n1 === 1 ? 'nube' : 'nubes'} en el cielo. Aparecen ${n2} más. ¿Cuántas nubes ves ahora?`,
    operation: '+', data1Label: 'Nubes veías', data1Unit: 'nubes', data2Label: 'Aparecen', data2Unit: 'nubes',
    resultLabelTemplate: (res) => `Ahora ves ${res} ${res === 1 ? 'nube' : 'nubes'}.`, icon: '☁️',
  },
  // Restas
  {
    id: 'g1_galletas_come_simple',
    problemTextTemplate: (n1, n2) => `Tienes ${n1} galleta${n1 === 1 ? '' : 's'}. Te comes ${n2}. ¿Cuántas galletas te quedan?`,
    operation: '-', data1Label: 'Galletas tenías', data1Unit: 'galletas', data2Label: 'Te comes', data2Unit: 'galletas',
    resultLabelTemplate: (res) => `Te quedan ${res} galleta${res === 1 ? '' : 's'}.`, icon: '🍪',
  },
  {
    id: 'g1_pelotas_pierde_simple',
    problemTextTemplate: (n1, n2) => `Juegas con ${n1} pelota${n1 === 1 ? '' : 's'}. Pierdes ${n2}. ¿Cuántas pelotas te quedan?`,
    operation: '-', data1Label: 'Pelotas tenías', data1Unit: 'pelotas', data2Label: 'Pierdes', data2Unit: 'pelotas',
    resultLabelTemplate: (res) => `Te quedan ${res} pelota${res === 1 ? '' : 's'}.`, icon: '⚽',
  },
  {
    id: 'g1_juguetes_presta_simple',
    problemTextTemplate: (n1, n2) => `Tenías ${n1} juguete${n1 === 1 ? '' : 's'}. Prestaste ${n2}. ¿Cuántos juguetes tienes ahora?`,
    operation: '-', data1Label: 'Juguetes tenías', data1Unit: 'juguetes', data2Label: 'Prestaste', data2Unit: 'juguetes',
    resultLabelTemplate: (res) => `Ahora tienes ${res} juguete${res === 1 ? '' : 's'}.`, icon: '🧸',
  },
  {
    id: 'g1_pájaros_vuelan_simple',
    problemTextTemplate: (n1, n2) => `Hay ${n1} pájaro${n1 === 1 ? '' : 's'} en el árbol. Se vuelan ${n2}. ¿Cuántos pájaros quedan?`,
    operation: '-', data1Label: 'Pájaros había', data1Unit: 'pájaros', data2Label: 'Se vuelan', data2Unit: 'pájaros',
    resultLabelTemplate: (res) => `Quedan ${res} pájaro${res === 1 ? '' : 's'}.`, icon: '🐦',
  },
  {
    id: 'g1_caramelos_comparte_simple',
    problemTextTemplate: (n1, n2) => `Tienes ${n1} caramelo${n1 === 1 ? '' : 's'}. Compartes ${n2}. ¿Cuántos caramelos te quedan?`,
    operation: '-', data1Label: 'Caramelos tenías', data1Unit: 'caramelos', data2Label: 'Compartes', data2Unit: 'caramelos',
    resultLabelTemplate: (res) => `Te quedan ${res} caramelo${res === 1 ? '' : 's'}.`, icon: '🍬',
  },
  {
    id: 'g1_estrellas_desaparecen_simple',
    problemTextTemplate: (n1, n2) => `En el cielo hay ${n1} ${n1 === 1 ? 'estrella' : 'estrellas'}. Desaparecen ${n2}. ¿Cuántas estrellas quedan?`,
    operation: '-', data1Label: 'Estrellas había', data1Unit: 'estrellas', data2Label: 'Desaparecen', data2Unit: 'estrellas',
    resultLabelTemplate: (res) => `Quedan ${res} ${res === 1 ? 'estrella' : 'estrellas'}.`, icon: '🌟',
  },
  {
    id: 'g1_burbujas_explotan_simple',
    problemTextTemplate: (n1, n2) => `Haces ${n1} ${n1 === 1 ? 'burbuja' : 'burbujas'}. Se explotan ${n2}. ¿Cuántas burbujas quedan?`,
    operation: '-', data1Label: 'Burbujas hiciste', data1Unit: 'burbujas', data2Label: 'Explotan', data2Unit: 'burbujas',
    resultLabelTemplate: (res) => `Quedan ${res} ${res === 1 ? 'burbuja' : 'burbujas'}.`, icon: '🫧',
  },
  {
    id: 'g1_velas_apagan_simple',
    problemTextTemplate: (n1, n2) => `Hay ${n1} ${n1 === 1 ? 'vela' : 'velas'} encendidas. Se apagan ${n2}. ¿Cuántas velas quedan prendidas?`,
    operation: '-', data1Label: 'Velas encendidas', data1Unit: 'velas', data2Label: 'Se apagan', data2Unit: 'velas',
    resultLabelTemplate: (res) => `Quedan ${res} ${res === 1 ? 'vela' : 'velas'} prendidas.`, icon: '🕯️',
  },
   {
    id: 'g1_botones_caen_simple',
    problemTextTemplate: (n1, n2) => `Una camisa tiene ${n1} ${n1 === 1 ? 'botón' : 'botones'}. Se caen ${n2}. ¿Cuántos botones quedan?`,
    operation: '-', data1Label: 'Botones tenía', data1Unit: 'botones', data2Label: 'Se caen', data2Unit: 'botones',
    resultLabelTemplate: (res) => `Quedan ${res} ${res === 1 ? 'botón' : 'botones'}.`, icon: '🔘',
  },
  {
    id: 'g1_hojas_caen_arbol_simple',
    problemTextTemplate: (n1, n2) => `Un árbol tiene ${n1} ${n1 === 1 ? 'hoja' : 'hojas'}. Se caen ${n2}. ¿Cuántas hojas le quedan al árbol?`,
    operation: '-', data1Label: 'Hojas tenía', data1Unit: 'hojas', data2Label: 'Se caen', data2Unit: 'hojas',
    resultLabelTemplate: (res) => `Al árbol le quedan ${res} ${res === 1 ? 'hoja' : 'hojas'}.`, icon: '🍂',
  },
];

// --- SCENARIOS FOR 1ST GRADE: Results < 100, simple 2-digit + 1-digit or tens ---
const firstGradeTensSimpleTwoDigitScenarios: Scenario[] = [
  // Sumas
  {
    id: 'g1_figus_decenas_suma',
    problemTextTemplate: (n1, n2) => `Tienes ${n1} figuritas. Te regalan ${n2} más. ¿Cuántas figuritas tienes ahora?`,
    operation: '+', data1Label: 'Figuritas tenías', data1Unit: 'figuritas', data2Label: 'Te regalan', data2Unit: 'figuritas',
    resultLabelTemplate: (res) => `Ahora tienes ${res} figuritas.`, icon: '✨',
  },
  {
    id: 'g1_puntos_juego_suma',
    problemTextTemplate: (n1, n2) => `En un juego, ganas ${n1} puntos y luego ${n2} puntos más. ¿Cuántos puntos tienes en total?`,
    operation: '+', data1Label: 'Puntos ganas', data1Unit: 'puntos', data2Label: 'Ganas más', data2Unit: 'puntos',
    resultLabelTemplate: (res) => `Tienes ${res} puntos en total.`, icon: '🎯',
  },
  {
    id: 'g1_crayones_caja_suma',
    problemTextTemplate: (n1, n2) => `Una caja tiene ${n1} crayones. Agregas ${n2} crayones más. ¿Cuántos crayones hay ahora?`,
    operation: '+', data1Label: 'Crayones había', data1Unit: 'crayones', data2Label: 'Agregas', data2Unit: 'crayones',
    resultLabelTemplate: (res) => `Ahora hay ${res} crayones.`, icon: '🖍️',
  },
  {
    id: 'g1_monedas_alcancia_suma',
    problemTextTemplate: (n1, n2) => `Pones ${n1} monedas en tu alcancía. Luego pones ${n2} monedas más. ¿Cuántas monedas pusiste en total?`,
    operation: '+', data1Label: 'Monedas pones', data1Unit: 'monedas', data2Label: 'Pones más', data2Unit: 'monedas',
    resultLabelTemplate: (res) => `Pusiste ${res} monedas en total.`, icon: '🪙',
  },
  {
    id: 'g1_pegatinas_album_suma',
    problemTextTemplate: (n1, n2) => `Tienes ${n1} pegatinas. Consigues ${n2} más. ¿Cuántas pegatinas tienes en total?`,
    operation: '+', data1Label: 'Pegatinas tenías', data1Unit: 'pegatinas', data2Label: 'Consigues más', data2Unit: 'pegatinas',
    resultLabelTemplate: (res) => `Tienes ${res} pegatinas en total.`, icon: '🌟',
  },
  {
    id: 'g1_cartas_mazo_suma',
    problemTextTemplate: (n1, n2) => `En un mazo hay ${n1} cartas. Se añaden ${n2} cartas nuevas. ¿Cuántas cartas hay ahora?`,
    operation: '+', data1Label: 'Cartas había', data1Unit: 'cartas', data2Label: 'Se añaden', data2Unit: 'cartas',
    resultLabelTemplate: (res) => `Ahora hay ${res} cartas.`, icon: '🃏',
  },
  {
    id: 'g1_bloques_construccion_suma',
    problemTextTemplate: (n1, n2) => `Usas ${n1} bloques para una torre. Luego agregas ${n2} bloques más. ¿Cuántos bloques usaste?`,
    operation: '+', data1Label: 'Bloques usas', data1Unit: 'bloques', data2Label: 'Agregas más', data2Unit: 'bloques',
    resultLabelTemplate: (res) => `Usaste ${res} bloques.`, icon: '🧱',
  },
  {
    id: 'g1_canciones_escuchas_suma',
    problemTextTemplate: (n1, n2) => `Escuchas ${n1} canciones. Después escuchas ${n2} canciones más. ¿Cuántas canciones escuchaste?`,
    operation: '+', data1Label: 'Canciones escuchas', data1Unit: 'canciones', data2Label: 'Escuchas más', data2Unit: 'canciones',
    resultLabelTemplate: (res) => `Escuchaste ${res} canciones.`, icon: '🎶',
  },
  {
    id: 'g1_pasos_caminas_suma',
    problemTextTemplate: (n1, n2) => `Caminas ${n1} pasos. Luego caminas ${n2} pasos más. ¿Cuántos pasos caminaste en total?`,
    operation: '+', data1Label: 'Pasos caminas', data1Unit: 'pasos', data2Label: 'Caminas más', data2Unit: 'pasos',
    resultLabelTemplate: (res) => `Caminaste ${res} pasos en total.`, icon: '👣',
  },
  {
    id: 'g1_animalitos_granja_suma',
    problemTextTemplate: (n1, n2) => `En una granja hay ${n1} pollitos. Nacen ${n2} más. ¿Cuántos pollitos hay ahora?`,
    operation: '+', data1Label: 'Pollitos había', data1Unit: 'pollitos', data2Label: 'Nacen más', data2Unit: 'pollitos',
    resultLabelTemplate: (res) => `Ahora hay ${res} pollitos.`, icon: '🐤',
  },
  // Restas
  {
    id: 'g1_dinero_gasta_resta',
    problemTextTemplate: (n1, n2) => `Tienes ${n1} pesos. Gastas ${n2} pesos en un helado. ¿Cuánto dinero te queda?`,
    operation: '-', data1Label: 'Pesos tenías', data1Unit: 'pesos', data2Label: 'Gastas', data2Unit: 'pesos',
    resultLabelTemplate: (res) => `Te quedan ${res} pesos.`, icon: '💸',
  },
  {
    id: 'g1_galletas_caja_resta',
    problemTextTemplate: (n1, n2) => `Una caja tiene ${n1} galletas. Te comes ${n2}. ¿Cuántas galletas quedan en la caja?`,
    operation: '-', data1Label: 'Galletas había', data1Unit: 'galletas', data2Label: 'Te comes', data2Unit: 'galletas',
    resultLabelTemplate: (res) => `Quedan ${res} galletas en la caja.`, icon: '🍪',
  },
  {
    id: 'g1_hojas_cuaderno_resta',
    problemTextTemplate: (n1, n2) => `Tu cuaderno tiene ${n1} hojas. Usas ${n2} hojas para dibujar. ¿Cuántas hojas quedan?`,
    operation: '-', data1Label: 'Hojas tenía', data1Unit: 'hojas', data2Label: 'Usas', data2Unit: 'hojas',
    resultLabelTemplate: (res) => `Quedan ${res} hojas.`, icon: '🗒️',
  },
  {
    id: 'g1_pasajeros_tren_resta',
    problemTextTemplate: (n1, n2) => `En el tren viajan ${n1} personas. Se bajan ${n2} en una estación. ¿Cuántas personas siguen en el tren?`,
    operation: '-', data1Label: 'Personas viajaban', data1Unit: 'personas', data2Label: 'Se bajan', data2Unit: 'personas',
    resultLabelTemplate: (res) => `Siguen ${res} personas en el tren.`, icon: '🚆',
  },
  {
    id: 'g1_juguetes_guardados_resta',
    problemTextTemplate: (n1, n2) => `Tenías ${n1} juguetes. Guardaste ${n2} en una caja. ¿Cuántos juguetes te quedaron afuera?`,
    operation: '-', data1Label: 'Juguetes tenías', data1Unit: 'juguetes', data2Label: 'Guardaste', data2Unit: 'juguetes',
    resultLabelTemplate: (res) => `Te quedaron ${res} juguetes afuera.`, icon: '📦',
  },
  {
    id: 'g1_libros_leidos_resta',
    problemTextTemplate: (n1, n2) => `Tienes ${n1} libros por leer. Ya leíste ${n2}. ¿Cuántos libros te faltan leer?`,
    operation: '-', data1Label: 'Libros por leer', data1Unit: 'libros', data2Label: 'Leíste', data2Unit: 'libros',
    resultLabelTemplate: (res) => `Te faltan leer ${res} libros.`, icon: '📖',
  },
  {
    id: 'g1_globos_fiesta_revientan_resta',
    problemTextTemplate: (n1, n2) => `Había ${n1} globos en la fiesta. Se reventaron ${n2}. ¿Cuántos globos quedaron?`,
    operation: '-', data1Label: 'Globos había', data1Unit: 'globos', data2Label: 'Reventaron', data2Unit: 'globos',
    resultLabelTemplate: (res) => `Quedaron ${res} globos.`, icon: '🎈',
  },
  {
    id: 'g1_manzanas_cesta_comen_resta',
    problemTextTemplate: (n1, n2) => `Una cesta tiene ${n1} manzanas. Te comes ${n2} manzanas. ¿Cuántas quedan en la cesta?`,
    operation: '-', data1Label: 'Manzanas había', data1Unit: 'manzanas', data2Label: 'Te comes', data2Unit: 'manzanas',
    resultLabelTemplate: (res) => `Quedan ${res} manzanas en la cesta.`, icon: '🧺',
  },
  {
    id: 'g1_flores_ramo_marchitan_resta',
    problemTextTemplate: (n1, n2) => `Un ramo tiene ${n1} flores. Se marchitan ${n2}. ¿Cuántas flores bonitas quedan?`,
    operation: '-', data1Label: 'Flores había', data1Unit: 'flores', data2Label: 'Se marchitan', data2Unit: 'flores',
    resultLabelTemplate: (res) => `Quedan ${res} flores bonitas.`, icon: '💐',
  },
  {
    id: 'g1_peces_pecera_regalan_resta',
    problemTextTemplate: (n1, n2) => `Tienes ${n1} peces en tu pecera. Regalas ${n2} a un amigo. ¿Cuántos peces te quedan?`,
    operation: '-', data1Label: 'Peces tenías', data1Unit: 'peces', data2Label: 'Regalas', data2Unit: 'peces',
    resultLabelTemplate: (res) => `Te quedan ${res} peces.`, icon: '🐠',
  },
];


// --- Existing Scenarios (from user's initial files) ---
const generalScenarios: Scenario[] = [
  {
    id: 'tractor_cereales',
    problemTextTemplate: (n1, n2) => `Un tractor transporta ${n1} kilos de maíz y ${n2} kilos de trigo. ¿Cuántos kilos de cereal transporta en total?`,
    operation: '+',
    data1Label: 'De maíz',
    data1Unit: 'kilos',
    data2Label: 'De trigo',
    data2Unit: 'kilos',
    resultLabelTemplate: (res) => `El tractor transporta ${res} kilos de cereal en total.`,
    icon: '🚜',
  },
  {
    id: 'pasajeros_colectivo_suben',
    problemTextTemplate: (n1, n2) => `En un colectivo viajan ${n1} pasajeros. En la primera parada, suben ${n2} pasajeros más. ¿Cuántos pasajeros hay ahora en el colectivo?`,
    operation: '+',
    data1Label: 'Pasajeros iniciales',
    data1Unit: 'pasajeros',
    data2Label: 'Suben en parada',
    data2Unit: 'pasajeros',
    resultLabelTemplate: (res) => `Ahora hay ${res} pasajeros en el colectivo.`,
    icon: '🚌',
  },
  {
    id: 'pasajeros_colectivo_bajan',
    problemTextTemplate: (n1, n2) => `Un colectivo lleva ${n1} pasajeros. En una parada se bajan ${n2} pasajeros. ¿Cuántos pasajeros quedan en el colectivo?`,
    operation: '-',
    data1Label: 'Pasajeros había',
    data1Unit: 'pasajeros',
    data2Label: 'Pasajeros bajan',
    data2Unit: 'pasajeros',
    resultLabelTemplate: (res) => `Quedan ${res} pasajeros en el colectivo.`,
    icon: '🚌',
  },
  {
    id: 'galletas_caja',
    problemTextTemplate: (n1, n2) => `María tenía ${n1} galletas en una caja. Si se comió ${n2} galletas, ¿cuántas galletas le quedan?`,
    operation: '-',
    data1Label: 'Galletas tenía',
    data1Unit: 'galletas',
    data2Label: 'Galletas comió',
    data2Unit: 'galletas',
    resultLabelTemplate: (res) => `A María le quedan ${res} galletas.`,
    icon: '🍪',
  },
  {
    id: 'libros_estanteria_general',
    problemTextTemplate: (n1, n2) => `En una estantería hay ${n1} libros de cuentos y ${n2} libros de ciencia. ¿Cuántos libros hay en total en la estantería?`,
    operation: '+',
    data1Label: 'Libros de cuentos',
    data1Unit: 'libros',
    data2Label: 'Libros de ciencia',
    data2Unit: 'libros',
    resultLabelTemplate: (res) => `En la estantería hay ${res} libros en total.`,
    icon: '📚',
  },
  {
    id: 'plata_ahorrada_gasta',
    problemTextTemplate: (n1, n2) => `Laura tenía ${n1} pesos ahorrados. Si gastó ${n2} pesos en un juguete, ¿cuánta plata le queda?`,
    operation: '-',
    data1Label: 'Plata ahorrada',
    data1Unit: 'pesos',
    data2Label: 'Plata gastada',
    data2Unit: 'pesos',
    resultLabelTemplate: (res) => `A Laura le quedan ${res} pesos.`,
    icon: '💰',
  },
  {
    id: 'plata_recibe_total',
    problemTextTemplate: (n1, n2) => `Carlos tiene ${n1} pesos en su alcancía. Su abuela le da ${n2} pesos por su cumpleaños. ¿Cuánta plata tiene ahora Carlos?`,
    operation: '+',
    data1Label: 'Plata tenía',
    data1Unit: 'pesos',
    data2Label: 'Plata recibe',
    data2Unit: 'pesos',
    resultLabelTemplate: (res) => `Carlos tiene ahora ${res} pesos.`,
    icon: '🎁',
  },
  {
    id: 'arboles_parque_plantan',
    problemTextTemplate: (n1, n2) => `En un parque había ${n1} árboles. Plantaron ${n2} árboles más. ¿Cuántos árboles hay ahora en el parque?`,
    operation: '+',
    data1Label: 'Árboles había',
    data1Unit: 'árboles',
    data2Label: 'Árboles plantaron',
    data2Unit: 'árboles',
    resultLabelTemplate: (res) => `Ahora hay ${res} árboles en el parque.`,
    icon: '🌳',
  },
  {
    id: 'arboles_parque_quitan',
    problemTextTemplate: (n1, n2) => `En un bosque había ${n1} pinos. Si se talaron ${n2} pinos, ¿cuántos pinos quedaron?`,
    operation: '-',
    data1Label: 'Pinos había',
    data1Unit: 'pinos',
    data2Label: 'Pinos talados',
    data2Unit: 'pinos',
    resultLabelTemplate: (res) => `Quedaron ${res} pinos.`,
    icon: '🌲',
  },
  {
    id: 'figuritas_album_regala',
    problemTextTemplate: (n1, n2) => `Pedro tiene un álbum con ${n1} figuritas. Su amigo le regaló ${n2} figuritas más. ¿Cuántas figuritas tiene Pedro en total?`,
    operation: '+',
    data1Label: 'Figuritas tenía',
    data1Unit: 'figuritas',
    data2Label: 'Figuritas regaladas',
    data2Unit: 'figuritas',
    resultLabelTemplate: (res) => `Pedro tiene ${res} figuritas en total.`,
    icon: '🖼️',
  },
  {
    id: 'figuritas_album_pierde',
    problemTextTemplate: (n1, n2) => `Ana tiene ${n1} figuritas repetidas. Si pierde ${n2} de ellas, ¿cuántas figuritas repetidas le quedan?`,
    operation: '-',
    data1Label: 'Figuritas repetidas',
    data1Unit: 'figuritas',
    data2Label: 'Figuritas perdidas',
    data2Unit: 'figuritas',
    resultLabelTemplate: (res) => `A Ana le quedan ${res} figuritas repetidas.`,
    icon: '🃏',
  },
  {
    id: 'flores_jardin',
    problemTextTemplate: (n1, n2) => `En un jardín florecieron ${n1} rosas rojas y ${n2} rosas blancas. ¿Cuántas rosas florecieron en total?`,
    operation: '+',
    data1Label: 'Rosas rojas',
    data1Unit: 'rosas',
    data2Label: 'Rosas blancas',
    data2Unit: 'rosas',
    resultLabelTemplate: (res) => `Florecieron ${res} rosas en total.`,
    icon: '🌹',
  },
  {
    id: 'flores_marchitan',
    problemTextTemplate: (n1, n2) => `Un florero tenía ${n1} margaritas. Se marchitaron ${n2} margaritas. ¿Cuántas margaritas frescas quedan?`,
    operation: '-',
    data1Label: 'Margaritas había',
    data1Unit: 'margaritas',
    data2Label: 'Se marchitaron',
    data2Unit: 'margaritas',
    resultLabelTemplate: (res) => `Quedan ${res} margaritas frescas.`,
    icon: '🌼',
  },
  {
    id: 'piezas_rompecabezas',
    problemTextTemplate: (n1, n2) => `Un rompecabezas tiene ${n1} piezas. Si ya se han colocado ${n2} piezas, ¿cuántas piezas faltan por colocar?`,
    operation: '-',
    data1Label: 'Total piezas',
    data1Unit: 'piezas',
    data2Label: 'Piezas colocadas',
    data2Unit: 'piezas',
    resultLabelTemplate: (res) => `Faltan ${res} piezas por colocar.`,
    icon: '🧩',
  },
  {
    id: 'animales_granja',
    problemTextTemplate: (n1, n2) => `En una granja hay ${n1} gallinas y ${n2} vacas. ¿Cuántos animales de estos dos tipos hay en la granja?`,
    operation: '+',
    data1Label: 'Gallinas',
    data1Unit: 'gallinas',
    data2Label: 'Vacas',
    data2Unit: 'vacas',
    resultLabelTemplate: (res) => `Hay ${res} animales (gallinas y vacas) en la granja.`,
    icon: '🐔',
  },
  {
    id: 'peces_acuario_venden',
    problemTextTemplate: (n1, n2) => `En una tienda de mascotas había ${n1} peces en un acuario. Si vendieron ${n2} peces, ¿cuántos quedan?`,
    operation: '-',
    data1Label: 'Peces había',
    data1Unit: 'peces',
    data2Label: 'Peces vendidos',
    data2Unit: 'peces',
    resultLabelTemplate: (res) => `Quedan ${res} peces en el acuario.`,
    icon: '🐠',
  },
  {
    id: 'manzanas_cesta_compra',
    problemTextTemplate: (n1, n2) => `Una cesta tiene ${n1} manzanas rojas. Se añaden ${n2} manzanas verdes. ¿Cuántas manzanas hay ahora en la cesta?`,
    operation: '+',
    data1Label: 'Manzanas rojas',
    data1Unit: 'manzanas',
    data2Label: 'Manzanas verdes',
    data2Unit: 'manzanas',
    resultLabelTemplate: (res) => `Ahora hay ${res} manzanas en la cesta.`,
    icon: '🍎',
  },
  {
    id: 'naranjas_bolsa_come',
    problemTextTemplate: (n1, n2) => `Juan compró una bolsa con ${n1} naranjas. Si se come ${n2} naranjas, ¿cuántas le quedan?`,
    operation: '-',
    data1Label: 'Naranjas compró',
    data1Unit: 'naranjas',
    data2Label: 'Naranjas comió',
    data2Unit: 'naranjas',
    resultLabelTemplate: (res) => `A Juan le quedan ${res} naranjas.`,
    icon: '🍊',
  },
  {
    id: 'alumnos_clase',
    problemTextTemplate: (n1, n2) => `En una clase hay ${n1} nenes y ${n2} nenas. ¿Cuántos alumnos hay en total?`,
    operation: '+',
    data1Label: 'Nenes',
    data1Unit: 'alumnos',
    data2Label: 'Nenas',
    data2Unit: 'alumnas',
    resultLabelTemplate: (res) => `Hay ${res} alumnos en total en la clase.`,
    icon: '🧑‍🏫',
  },
  {
    id: 'alumnos_excursion_faltan',
    problemTextTemplate: (n1, n2) => `A una excursión iban a ir ${n1} alumnos. Si finalmente ${n2} alumnos no pudieron ir, ¿cuántos alumnos fueron a la excursión?`,
    operation: '-',
    data1Label: 'Alumnos iban',
    data1Unit: 'alumnos',
    data2Label: 'Alumnos faltaron',
    data2Unit: 'alumnos',
    resultLabelTemplate: (res) => `Fueron ${res} alumnos a la excursión.`,
    icon: '🎒',
  },
  {
    id: 'paginas_libro',
    problemTextTemplate: (n1, n2) => `Un libro tiene ${n1} páginas. Si ya he leído ${n2} páginas, ¿cuántas me faltan por leer?`,
    operation: '-',
    data1Label: 'Total páginas',
    data1Unit: 'páginas',
    data2Label: 'Páginas leídas',
    data2Unit: 'páginas',
    resultLabelTemplate: (res) => `Me faltan ${res} páginas por leer.`,
    icon: '📖',
  },
  {
    id: 'canicas_bolsa_gana',
    problemTextTemplate: (n1, n2) => `Luis tiene ${n1} canicas en una bolsa. Jugando con un amigo, gana ${n2} canicas más. ¿Cuántas canicas tiene ahora Luis?`,
    operation: '+',
    data1Label: 'Canicas tenía',
    data1Unit: 'canicas',
    data2Label: 'Canicas ganó',
    data2Unit: 'canicas',
    resultLabelTemplate: (res) => `Luis tiene ahora ${res} canicas.`,
    icon: '🔮', 
  },
  {
    id: 'globos_fiesta_explotan',
    problemTextTemplate: (n1, n2) => `Para una fiesta se inflaron ${n1} globos. Si se explotaron ${n2} globos, ¿cuántos globos quedaron inflados?`,
    operation: '-',
    data1Label: 'Globos inflados',
    data1Unit: 'globos',
    data2Label: 'Globos explotaron',
    data2Unit: 'globos',
    resultLabelTemplate: (res) => `Quedaron ${res} globos inflados.`,
    icon: '🎈',
  },
  {
    id: 'autos_estacionamiento_entran',
    problemTextTemplate: (n1, n2) => `En un estacionamiento hay ${n1} autos. Durante la mañana entran ${n2} autos más. ¿Cuántos autos hay ahora?`,
    operation: '+',
    data1Label: 'Autos había',
    data1Unit: 'autos',
    data2Label: 'Autos entran',
    data2Unit: 'autos',
    resultLabelTemplate: (res) => `Ahora hay ${res} autos en el estacionamiento.`,
    icon: '🚗',
  },
  {
    id: 'autos_estacionamiento_salen',
    problemTextTemplate: (n1, n2) => `Un estacionamiento tiene ${n1} lugares ocupados. Si salen ${n2} autos, ¿cuántos lugares ocupados quedan?`,
    operation: '-',
    data1Label: 'Lugares ocupados',
    data1Unit: 'lugares',
    data2Label: 'Autos salen',
    data2Unit: 'autos',
    resultLabelTemplate: (res) => `Quedan ${res} lugares ocupados.`,
    icon: '🅿️',
  },
  {
    id: 'lapices_estuche_pierde',
    problemTextTemplate: (n1, n2) => `Mario tenía ${n1} lápices de colores en su cartuchera. Perdió ${n2} lápices. ¿Cuántos lápices le quedan?`,
    operation: '-',
    data1Label: 'Lápices tenía',
    data1Unit: 'lápices',
    data2Label: 'Lápices perdió',
    data2Unit: 'lápices',
    resultLabelTemplate: (res) => `A Mario le quedan ${res} lápices.`,
    icon: '✏️',
  },
  {
    id: 'juguetes_caja_guarda_general', 
    problemTextTemplate: (n1, n2) => `En una caja había ${n1} juguetes. Mamá guardó ${n2} juguetes más. ¿Cuántos juguetes hay ahora en la caja?`,
    operation: '+',
    data1Label: 'Juguetes había',
    data1Unit: 'juguetes',
    data2Label: 'Juguetes guardó',
    data2Unit: 'juguetes',
    resultLabelTemplate: (res) => `Ahora hay ${res} juguetes en la caja.`,
    icon: '🧸',
  },
  {
    id: 'pajaros_arbol_vuelan',
    problemTextTemplate: (n1, n2) => `En un árbol había ${n1} pájaros cantando. Si ${n2} pájaros se fueron volando, ¿cuántos pájaros quedaron en el árbol?`,
    operation: '-',
    data1Label: 'Pájaros había',
    data1Unit: 'pájaros',
    data2Label: 'Pájaros volaron',
    data2Unit: 'pájaros',
    resultLabelTemplate: (res) => `Quedaron ${res} pájaros en el árbol.`,
    icon: '🐦',
  },
  {
    id: 'caramelos_bolsa_reparte',
    problemTextTemplate: (n1, n2) => `Una bolsa tiene ${n1} caramelos. Si se reparten ${n2} caramelos entre los amigos, ¿cuántos caramelos quedan en la bolsa?`,
    operation: '-',
    data1Label: 'Caramelos había',
    data1Unit: 'caramelos',
    data2Label: 'Caramelos repartidos',
    data2Unit: 'caramelos',
    resultLabelTemplate: (res) => `Quedan ${res} caramelos en la bolsa.`,
    icon: '🍬',
  },
  {
    id: 'fotos_album_pega',
    problemTextTemplate: (n1, n2) => `Un álbum de fotos tiene ${n1} fotos pegadas. Hoy se han pegado ${n2} fotos más. ¿Cuántas fotos tiene ahora el álbum?`,
    operation: '+',
    data1Label: 'Fotos había',
    data1Unit: 'fotos',
    data2Label: 'Fotos pegadas hoy',
    data2Unit: 'fotos',
    resultLabelTemplate: (res) => `El álbum tiene ahora ${res} fotos.`,
    icon: '📸',
  },
  {
    id: 'ovejas_rebaño_pierden',
    problemTextTemplate: (n1, n2) => `Un pastor tiene un rebaño de ${n1} ovejas. Si se le pierden ${n2} ovejas, ¿cuántas le quedan?`,
    operation: '-',
    data1Label: 'Ovejas tenía',
    data1Unit: 'ovejas',
    data2Label: 'Ovejas perdidas',
    data2Unit: 'ovejas',
    resultLabelTemplate: (res) => `Al pastor le quedan ${res} ovejas.`,
    icon: '🐑',
  },
  {
    id: 'figuritas_coleccion_consigue',
    problemTextTemplate: (n1, n2) => `En mi colección tengo ${n1} figuritas. Hoy he conseguido ${n2} figuritas nuevas. ¿Cuántas figuritas tengo ahora?`,
    operation: '+',
    data1Label: 'Figuritas tenía',
    data1Unit: 'figuritas',
    data2Label: 'Figuritas nuevas',
    data2Unit: 'figuritas',
    resultLabelTemplate: (res) => `Ahora tengo ${res} figuritas.`,
    icon: '🌟',
  },
  {
    id: 'jugos_heladera_beben',
    problemTextTemplate: (n1, n2) => `En la heladera había ${n1} jugos. Mis hermanos y yo nos hemos tomado ${n2} jugos. ¿Cuántos jugos quedan?`,
    operation: '-',
    data1Label: 'Jugos había',
    data1Unit: 'jugos',
    data2Label: 'Jugos tomados',
    data2Unit: 'jugos',
    resultLabelTemplate: (res) => `Quedan ${res} jugos en la heladera.`,
    icon: '🥤',
  },
  {
    id: 'remeras_armario_compra',
    problemTextTemplate: (n1, n2) => `En el armario tengo ${n1} remeras. Me han comprado ${n2} remeras nuevas. ¿Cuántas remeras tengo ahora?`,
    operation: '+',
    data1Label: 'Remeras tenía',
    data1Unit: 'remeras',
    data2Label: 'Remeras nuevas',
    data2Unit: 'remeras',
    resultLabelTemplate: (res) => `Ahora tengo ${res} remeras.`,
    icon: '👕',
  },
  {
    id: 'bombones_caja_come',
    problemTextTemplate: (n1, n2) => `Una caja tenía ${n1} bombones. Me he comido ${n2} bombones. ¿Cuántos bombones quedan en la caja?`,
    operation: '-',
    data1Label: 'Bombones había',
    data1Unit: 'bombones',
    data2Label: 'Bombones comidos',
    data2Unit: 'bombones',
    resultLabelTemplate: (res) => `Quedan ${res} bombones en la caja.`,
    icon: '🍫',
  },
  {
    id: 'colores_caja_añade',
    problemTextTemplate: (n1, n2) => `Una caja de pinturas tiene ${n1} colores. Si añadimos ${n2} colores más, ¿cuántos colores tendrá la caja?`,
    operation: '+',
    data1Label: 'Colores tenía',
    data1Unit: 'colores',
    data2Label: 'Colores añadidos',
    data2Unit: 'colores',
    resultLabelTemplate: (res) => `La caja tendrá ${res} colores.`,
    icon: '🎨',
  },
  {
    id: 'sillas_aula_retiran',
    problemTextTemplate: (n1, n2) => `En un aula hay ${n1} sillas. Si se retiran ${n2} sillas para limpiarlas, ¿cuántas sillas quedan en el aula?`,
    operation: '-',
    data1Label: 'Sillas había',
    data1Unit: 'sillas',
    data2Label: 'Sillas retiradas',
    data2Unit: 'sillas',
    resultLabelTemplate: (res) => `Quedan ${res} sillas en el aula.`,
    icon: '🪑',
  },
  {
    id: 'barcos_puerto_llegan',
    problemTextTemplate: (n1, n2) => `En un puerto hay ${n1} barcos. Si llegan ${n2} barcos más, ¿cuántos barcos hay ahora en el puerto?`,
    operation: '+',
    data1Label: 'Barcos había',
    data1Unit: 'barcos',
    data2Label: 'Barcos llegan',
    data2Unit: 'barcos',
    resultLabelTemplate: (res) => `Ahora hay ${res} barcos en el puerto.`,
    icon: '⛵',
  },
  {
    id: 'aviones_aeropuerto_despegan',
    problemTextTemplate: (n1, n2) => `En un aeropuerto hay ${n1} aviones listos para volar. Si despegan ${n2} aviones, ¿cuántos quedan en tierra?`,
    operation: '-',
    data1Label: 'Aviones listos',
    data1Unit: 'aviones',
    data2Label: 'Aviones despegan',
    data2Unit: 'aviones',
    resultLabelTemplate: (res) => `Quedan ${res} aviones en tierra.`,
    icon: '✈️',
  },
  {
    id: 'herramientas_caja_añade',
    problemTextTemplate: (n1, n2) => `Papá tiene una caja con ${n1} herramientas. Si compra ${n2} herramientas más, ¿cuántas tendrá ahora?`,
    operation: '+',
    data1Label: 'Herramientas tenía',
    data1Unit: 'herramientas',
    data2Label: 'Herramientas compró',
    data2Unit: 'herramientas',
    resultLabelTemplate: (res) => `Papá tendrá ahora ${res} herramientas.`,
    icon: '🛠️',
  },
  {
    id: 'tornillos_caja_usa',
    problemTextTemplate: (n1, n2) => `Una caja contiene ${n1} tornillos. Si se usan ${n2} tornillos para un mueble, ¿cuántos quedan?`,
    operation: '-',
    data1Label: 'Tornillos había',
    data1Unit: 'tornillos',
    data2Label: 'Tornillos usados',
    data2Unit: 'tornillos',
    resultLabelTemplate: (res) => `Quedan ${res} tornillos en la caja.`,
    icon: '🔩',
  },
   {
    id: 'perros_parque_llegan',
    problemTextTemplate: (n1, n2) => `En el parque están jugando ${n1} perros. Si llegan ${n2} perros más, ¿cuántos perros hay jugando ahora?`,
    operation: '+',
    data1Label: 'Perros jugando',
    data1Unit: 'perros',
    data2Label: 'Perros llegan',
    data2Unit: 'perros',
    resultLabelTemplate: (res) => `Ahora hay ${res} perros jugando en el parque.`,
    icon: '🐕',
  },
  {
    id: 'gatos_casa_adoptan',
    problemTextTemplate: (n1, n2) => `En una casa viven ${n1} gatos. Si la familia adopta ${n2} gatos más, ¿cuántos gatos viven ahora en la casa?`,
    operation: '+',
    data1Label: 'Gatos vivían',
    data1Unit: 'gatos',
    data2Label: 'Gatos adoptan',
    data2Unit: 'gatos',
    resultLabelTemplate: (res) => `Ahora viven ${res} gatos en la casa.`,
    icon: '🐈',
  },
  {
    id: 'nubes_cielo_desaparecen',
    problemTextTemplate: (n1, n2) => `Por la mañana había ${n1} nubes en el cielo. Al mediodía, ${n2} nubes se habían disipado. ¿Cuántas nubes quedan?`,
    operation: '-',
    data1Label: 'Nubes había',
    data1Unit: 'nubes',
    data2Label: 'Nubes disipadas',
    data2Unit: 'nubes',
    resultLabelTemplate: (res) => `Quedan ${res} nubes en el cielo.`,
    icon: '☁️',
  },
  {
    id: 'estrellas_noche_cuento',
    problemTextTemplate: (n1, n2) => `Anoche conté ${n1} estrellas brillantes. Luego, conté otras ${n2} estrellas más débiles. ¿Cuántas estrellas conté en total?`,
    operation: '+',
    data1Label: 'Estrellas brillantes',
    data1Unit: 'estrellas',
    data2Label: 'Estrellas débiles',
    data2Unit: 'estrellas',
    resultLabelTemplate: (res) => `Conté ${res} estrellas en total.`,
    icon: '🌠',
  },
  {
    id: 'botellas_agua_reciclan',
    problemTextTemplate: (n1, n2) => `En una semana, una familia juntó ${n1} botellas de plástico para reciclar. La semana siguiente, juntaron ${n2} botellas. ¿Cuántas botellas juntaron en total?`,
    operation: '+',
    data1Label: 'Botellas semana 1',
    data1Unit: 'botellas',
    data2Label: 'Botellas semana 2',
    data2Unit: 'botellas',
    resultLabelTemplate: (res) => `Juntaron ${res} botellas en total.`,
    icon: '♻️',
  },
  {
    id: 'hojas_cuaderno_arranca',
    problemTextTemplate: (n1, n2) => `Mi cuaderno tenía ${n1} hojas. Arranqué ${n2} hojas para hacer un dibujo. ¿Cuántas hojas le quedan al cuaderno?`,
    operation: '-',
    data1Label: 'Hojas tenía',
    data1Unit: 'hojas',
    data2Label: 'Hojas arrancadas',
    data2Unit: 'hojas',
    resultLabelTemplate: (res) => `Al cuaderno le quedan ${res} hojas.`,
    icon: '🗒️',
  },
  {
    id: 'huevos_carton_usan',
    problemTextTemplate: (n1, n2) => `Un maple de huevos tiene ${n1} huevos. Si usamos ${n2} para hacer una tortilla, ¿cuántos huevos quedan?`,
    operation: '-',
    data1Label: 'Huevos había',
    data1Unit: 'huevos',
    data2Label: 'Huevos usados',
    data2Unit: 'huevos',
    resultLabelTemplate: (res) => `Quedan ${res} huevos en el maple.`,
    icon: '🥚',
  },
  {
    id: 'tren_vagones_añaden',
    problemTextTemplate: (n1, n2) => `Un tren tiene ${n1} vagones. En la estación le añaden ${n2} vagones más. ¿Cuántos vagones tiene ahora el tren?`,
    operation: '+',
    data1Label: 'Vagones tenía',
    data1Unit: 'vagones',
    data2Label: 'Vagones añadidos',
    data2Unit: 'vagones',
    resultLabelTemplate: (res) => `El tren tiene ahora ${res} vagones.`,
    icon: '🚆',
  },
  {
    id: 'puntos_juego_gana',
    problemTextTemplate: (n1, n2) => `En un videojuego, tenías ${n1} puntos y ganaste ${n2} puntos más. ¿Cuántos puntos tienes ahora?`,
    operation: '+',
    data1Label: 'Puntos iniciales', data1Unit: 'puntos',
    data2Label: 'Puntos ganados', data2Unit: 'puntos',
    resultLabelTemplate: (res) => `Ahora tienes ${res} puntos.`,
    icon: '🎯',
  },
  {
    id: 'cromos_cambia',
    problemTextTemplate: (n1, n2) => `Tenías ${n1} cromos repetidos. Cambiaste ${n2} con un amigo. ¿Cuántos cromos repetidos te quedan?`,
    operation: '-',
    data1Label: 'Cromos repetidos', data1Unit: 'cromos',
    data2Label: 'Cromos cambiados', data2Unit: 'cromos',
    resultLabelTemplate: (res) => `Te quedan ${res} cromos repetidos.`,
    icon: '✨',
  },
  {
    id: 'paginas_libro_lunes_martes',
    problemTextTemplate: (n1, n2) => `Sofía leyó ${n1} páginas de un libro el lunes y ${n2} páginas el martes. ¿Cuántas páginas leyó en total?`,
    operation: '+',
    data1Label: 'Páginas lunes', data1Unit: 'páginas',
    data2Label: 'Páginas martes', data2Unit: 'páginas',
    resultLabelTemplate: (res) => `Sofía leyó ${res} páginas en total.`,
    icon: '📚',
  },
  {
    id: 'ovejas_granjero_vende',
    problemTextTemplate: (n1, n2) => `Un granjero tenía ${n1} ovejas y vendió ${n2}. ¿Cuántas ovejas le quedan?`,
    operation: '-',
    data1Label: 'Ovejas tenía', data1Unit: 'ovejas',
    data2Label: 'Ovejas vendió', data2Unit: 'ovejas',
    resultLabelTemplate: (res) => `Al granjero le quedan ${res} ovejas.`,
    icon: '🐑',
  },
  {
    id: 'flores_jardin_rojas_amarillas',
    problemTextTemplate: (n1, n2) => `En un jardín hay ${n1} flores rojas y ${n2} flores amarillas. ¿Cuántas flores hay en total?`,
    operation: '+',
    data1Label: 'Flores rojas', data1Unit: 'flores',
    data2Label: 'Flores amarillas', data2Unit: 'flores',
    resultLabelTemplate: (res) => `En el jardín hay ${res} flores en total.`,
    icon: '🌷',
  },
  {
    id: 'caramelos_pablo_regala',
    problemTextTemplate: (n1, n2) => `Pablo tenía ${n1} caramelos y regaló ${n2} a su amigo. ¿Cuántos caramelos le quedan?`,
    operation: '-',
    data1Label: 'Caramelos tenía', data1Unit: 'caramelos',
    data2Label: 'Caramelos regaló', data2Unit: 'caramelos',
    resultLabelTemplate: (res) => `A Pablo le quedan ${res} caramelos.`,
    icon: '🍬',
  },
  {
    id: 'goles_futbol_equipo',
    problemTextTemplate: (n1, n2) => `Un equipo de fútbol marcó ${n1} goles en el primer tiempo y ${n2} goles en el segundo. ¿Cuántos goles marcó en total?`,
    operation: '+',
    data1Label: 'Goles 1er tiempo', data1Unit: 'goles',
    data2Label: 'Goles 2do tiempo', data2Unit: 'goles',
    resultLabelTemplate: (res) => `El equipo marcó ${res} goles en total.`,
    icon: '⚽',
  },
  {
    id: 'pajaros_arbol_vuelan_lejos',
    problemTextTemplate: (n1, n2) => `Había ${n1} pájaros en un árbol. Si ${n2} volaron lejos, ¿cuántos quedaron?`,
    operation: '-',
    data1Label: 'Pájaros había', data1Unit: 'pájaros',
    data2Label: 'Pájaros volaron', data2Unit: 'pájaros',
    resultLabelTemplate: (res) => `Quedaron ${res} pájaros en el árbol.`,
    icon: '🐦',
  },
  {
    id: 'lapices_caja_azules_rojos',
    problemTextTemplate: (n1, n2) => `En una caja hay ${n1} lápices azules y ${n2} lápices rojos. ¿Cuántos lápices hay en total?`,
    operation: '+',
    data1Label: 'Lápices azules', data1Unit: 'lápices',
    data2Label: 'Lápices rojos', data2Unit: 'lápices',
    resultLabelTemplate: (res) => `Hay ${res} lápices en total en la caja.`,
    icon: '✏️',
  },
  {
    id: 'torta_porciones_comidas',
    problemTextTemplate: (n1, n2) => `Una torta tenía ${n1} porciones. Se comieron ${n2} porciones. ¿Cuántas porciones de torta quedan?`,
    operation: '-',
    data1Label: 'Porciones había', data1Unit: 'porciones',
    data2Label: 'Porciones comidas', data2Unit: 'porciones',
    resultLabelTemplate: (res) => `Quedan ${res} porciones de torta.`,
    icon: '🍰',
  },
  {
    id: 'peces_acuario_dorados_payaso',
    problemTextTemplate: (n1, n2) => `Un acuario tiene ${n1} peces dorados y ${n2} peces payaso. ¿Cuántos peces tiene en total?`,
    operation: '+',
    data1Label: 'Peces dorados', data1Unit: 'peces',
    data2Label: 'Peces payaso', data2Unit: 'peces',
    resultLabelTemplate: (res) => `El acuario tiene ${res} peces en total.`,
    icon: '🐠',
  },
  {
    id: 'huevos_mama_compra_usa',
    problemTextTemplate: (n1, n2) => `Mamá compró ${n1} huevos y usó ${n2} para una receta. ¿Cuántos huevos le quedan?`,
    operation: '-',
    data1Label: 'Huevos compró', data1Unit: 'huevos',
    data2Label: 'Huevos usó', data2Unit: 'huevos',
    resultLabelTemplate: (res) => `A mamá le quedan ${res} huevos.`,
    icon: '🥚',
  },
  {
    id: 'figuritas_juan_animales_dinosaurios',
    problemTextTemplate: (n1, n2) => `Juan tiene ${n1} figuritas de animales y ${n2} de dinosaurios. ¿Cuántas figuritas tiene en total?`,
    operation: '+',
    data1Label: 'Figuritas animales', data1Unit: 'figuritas',
    data2Label: 'Figuritas dinosaurios', data2Unit: 'figuritas',
    resultLabelTemplate: (res) => `Juan tiene ${res} figuritas en total.`,
    icon: '🦕',
  },
  {
    id: 'estacionamiento_lugares_libres',
    problemTextTemplate: (n1, n2) => `Un estacionamiento tiene capacidad para ${n1} autos. Si hay ${n2} autos estacionados, ¿cuántos lugares libres quedan?`,
    operation: '-',
    data1Label: 'Capacidad total', data1Unit: 'lugares',
    data2Label: 'Autos estacionados', data2Unit: 'autos',
    resultLabelTemplate: (res) => `Quedan ${res} lugares libres en el estacionamiento.`,
    icon: '🅿️',
  },
  {
    id: 'globos_fiesta_azules_verdes',
    problemTextTemplate: (n1, n2) => `En una fiesta hay ${n1} globos azules y ${n2} globos verdes. ¿Cuántos globos hay en total?`,
    operation: '+',
    data1Label: 'Globos azules', data1Unit: 'globos',
    data2Label: 'Globos verdes', data2Unit: 'globos',
    resultLabelTemplate: (res) => `Hay ${res} globos en total en la fiesta.`,
    icon: '🎈',
  },
  {
    id: 'tren_pasajeros_bajan_estacion',
    problemTextTemplate: (n1, n2) => `Un tren tenía ${n1} pasajeros. En una estación bajaron ${n2}. ¿Cuántos pasajeros continúan en el tren?`,
    operation: '-',
    data1Label: 'Pasajeros había', data1Unit: 'pasajeros',
    data2Label: 'Pasajeros bajaron', data2Unit: 'pasajeros',
    resultLabelTemplate: (res) => `Continúan ${res} pasajeros en el tren.`,
    icon: '🚆',
  },
  {
    id: 'medialunas_panadero_hornea',
    problemTextTemplate: (n1, n2) => `Un panadero horneó ${n1} medialunas por la mañana y ${n2} por la tarde. ¿Cuántas medialunas horneó en total?`,
    operation: '+',
    data1Label: 'Medialunas mañana', data1Unit: 'medialunas',
    data2Label: 'Medialunas tarde', data2Unit: 'medialunas',
    resultLabelTemplate: (res) => `El panadero horneó ${res} medialunas en total.`,
    icon: '🥐',
  },
  {
    id: 'libros_aventuras_biblioteca_prestan',
    problemTextTemplate: (n1, n2) => `Una biblioteca tenía ${n1} libros de aventuras. Prestaron ${n2}. ¿Cuántos libros de aventuras quedan?`,
    operation: '-',
    data1Label: 'Libros había', data1Unit: 'libros',
    data2Label: 'Libros prestaron', data2Unit: 'libros',
    resultLabelTemplate: (res) => `Quedan ${res} libros de aventuras en la biblioteca.`,
    icon: '📚',
  },
  {
    id: 'bolas_navidad_rojas_doradas',
    problemTextTemplate: (n1, n2) => `En un árbol de Navidad hay ${n1} bolas rojas y ${n2} bolas doradas. ¿Cuántas bolas hay en total?`,
    operation: '+',
    data1Label: 'Bolas rojas', data1Unit: 'bolas',
    data2Label: 'Bolas doradas', data2Unit: 'bolas',
    resultLabelTemplate: (res) => `Hay ${res} bolas en total en el árbol.`,
    icon: '🎄',
  },
  {
    id: 'rosas_florista_vende',
    problemTextTemplate: (n1, n2) => `Un florista tenía ${n1} rosas. Vendió ${n2} rosas. ¿Cuántas le quedan?`,
    operation: '-',
    data1Label: 'Rosas tenía', data1Unit: 'rosas',
    data2Label: 'Rosas vendió', data2Unit: 'rosas',
    resultLabelTemplate: (res) => `Al florista le quedan ${res} rosas.`,
    icon: '🌹',
  },
  {
    id: 'galletas_plato_chocolate_vainilla',
    problemTextTemplate: (n1, n2) => `En un plato hay ${n1} galletas de chocolate y ${n2} de vainilla. ¿Cuántas galletas hay en total?`,
    operation: '+',
    data1Label: 'Galletas chocolate', data1Unit: 'galletas',
    data2Label: 'Galletas vainilla', data2Unit: 'galletas',
    resultLabelTemplate: (res) => `Hay ${res} galletas en total en el plato.`,
    icon: '🍪',
  },
  {
    id: 'manzanas_arbol_caen',
    problemTextTemplate: (n1, n2) => `Un árbol tenía ${n1} manzanas. Se cayeron ${n2} manzanas. ¿Cuántas quedaron en el árbol?`,
    operation: '-',
    data1Label: 'Manzanas había', data1Unit: 'manzanas',
    data2Label: 'Manzanas cayeron', data2Unit: 'manzanas',
    resultLabelTemplate: (res) => `Quedaron ${res} manzanas en el árbol.`,
    icon: '🍎',
  },
  {
    id: 'figuritas_paquetes_total',
    problemTextTemplate: (n1, n2) => `Un paquete trae ${n1} figuritas y otro paquete trae ${n2} figuritas. ¿Cuántas figuritas hay en total?`,
    operation: '+',
    data1Label: 'Figuritas paquete 1', data1Unit: 'figuritas',
    data2Label: 'Figuritas paquete 2', data2Unit: 'figuritas',
    resultLabelTemplate: (res) => `Hay ${res} figuritas en total.`,
    icon: '✨',
  },
  {
    id: 'colectivo_asientos_libres',
    problemTextTemplate: (n1, n2) => `Un colectivo salió con ${n1} asientos. Si se ocuparon ${n2} asientos, ¿cuántos quedaron libres?`,
    operation: '-',
    data1Label: 'Asientos totales', data1Unit: 'asientos',
    data2Label: 'Asientos ocupados', data2Unit: 'asientos',
    resultLabelTemplate: (res) => `Quedaron ${res} asientos libres.`,
    icon: '🚌',
  },
  {
    id: 'metros_laura_recorre',
    problemTextTemplate: (n1, n2) => `Laura corrió ${n1} metros y luego caminó ${n2} metros más. ¿Cuántos metros recorrió en total?`,
    operation: '+',
    data1Label: 'Metros corrió', data1Unit: 'metros',
    data2Label: 'Metros caminó', data2Unit: 'metros',
    resultLabelTemplate: (res) => `Laura recorrió ${res} metros en total.`,
    icon: '🏃‍♀️',
  },
  {
    id: 'agua_bidon_riego',
    problemTextTemplate: (n1, n2) => `Un bidón tenía ${n1} litros de agua. Se usaron ${n2} litros para regar. ¿Cuántos litros quedan?`,
    operation: '-',
    data1Label: 'Litros había', data1Unit: 'litros',
    data2Label: 'Litros usados', data2Unit: 'litros',
    resultLabelTemplate: (res) => `Quedan ${res} litros en el bidón.`,
    icon: '💧',
  },
  {
    id: 'pollitos_granja_amarillos_marrones',
    problemTextTemplate: (n1, n2) => `En una granja hay ${n1} pollitos amarillos y ${n2} pollitos marrones. ¿Cuántos pollitos hay en total?`,
    operation: '+',
    data1Label: 'Pollitos amarillos', data1Unit: 'pollitos',
    data2Label: 'Pollitos marrones', data2Unit: 'pollitos',
    resultLabelTemplate: (res) => `Hay ${res} pollitos en total en la granja.`,
    icon: '🐤',
  },
  {
    id: 'juguetes_habitacion_junta',
    problemTextTemplate: (n1, n2) => `En tu habitación tienes ${n1} autitos y ${n2} muñecos. ¿Cuántos juguetes tienes en total?`,
    operation: '+',
    data1Label: 'Autitos', data1Unit: 'juguetes',
    data2Label: 'Muñecos', data2Unit: 'juguetes',
    resultLabelTemplate: (res) => `Tienes ${res} juguetes en total.`,
    icon: '🚗',
  },
  {
    id: 'bolitas_pierde_jardin',
    problemTextTemplate: (n1, n2) => `Tenías ${n1} bolitas y perdiste ${n2} jugando en el jardín. ¿Cuántas bolitas te quedan?`,
    operation: '-',
    data1Label: 'Bolitas tenías', data1Unit: 'bolitas',
    data2Label: 'Bolitas perdiste', data2Unit: 'bolitas',
    resultLabelTemplate: (res) => `Te quedan ${res} bolitas.`,
    icon: '🔵',
  },
  {
    id: 'cuentos_estante_compran',
    problemTextTemplate: (n1, n2) => `Había ${n1} cuentos en el estante. Mamá compró ${n2} cuentos nuevos. ¿Cuántos cuentos hay ahora?`,
    operation: '+',
    data1Label: 'Cuentos había', data1Unit: 'cuentos',
    data2Label: 'Cuentos nuevos', data2Unit: 'cuentos',
    resultLabelTemplate: (res) => `Ahora hay ${res} cuentos en el estante.`,
    icon: '📚',
  },
  {
    id: 'cartas_mazo_reparten',
    problemTextTemplate: (n1, n2) => `Un mazo tenía ${n1} cartas. Para jugar se repartieron ${n2} cartas. ¿Cuántas cartas quedaron en el mazo?`,
    operation: '-',
    data1Label: 'Cartas había', data1Unit: 'cartas',
    data2Label: 'Cartas repartidas', data2Unit: 'cartas',
    resultLabelTemplate: (res) => `Quedaron ${res} cartas en el mazo.`,
    icon: '♠️',
  },
  {
    id: 'mariposas_vuelan_juntas',
    problemTextTemplate: (n1, n2) => `En una flor había ${n1} mariposas. Llegaron ${n2} mariposas más. ¿Cuántas mariposas hay ahora?`,
    operation: '+',
    data1Label: 'Mariposas había', data1Unit: 'mariposas',
    data2Label: 'Mariposas llegaron', data2Unit: 'mariposas',
    resultLabelTemplate: (res) => `Ahora hay ${res} mariposas en la flor.`,
    icon: '🦋',
  },
  {
    id: 'dinosaurios_museo_prestan',
    problemTextTemplate: (n1, n2) => `El museo tenía ${n1} esqueletos de dinosaurios. Prestaron ${n2} a otra ciudad. ¿Cuántos quedaron?`,
    operation: '-',
    data1Label: 'Esqueletos tenía', data1Unit: 'esqueletos',
    data2Label: 'Esqueletos prestaron', data2Unit: 'esqueletos',
    resultLabelTemplate: (res) => `Quedaron ${res} esqueletos en el museo.`,
    icon: '🦴',
  },
  {
    id: 'helados_venden_kiosco',
    problemTextTemplate: (n1, n2) => `Un kiosco vendió ${n1} helados de frutilla y ${n2} helados de chocolate. ¿Cuántos helados vendió en total?`,
    operation: '+',
    data1Label: 'Helados frutilla', data1Unit: 'helados',
    data2Label: 'Helados chocolate', data2Unit: 'helados',
    resultLabelTemplate: (res) => `El kiosco vendió ${res} helados en total.`,
    icon: '🍦',
  },
  {
    id: 'facturas_panaderia_comen',
    problemTextTemplate: (n1, n2) => `En la panadería había ${n1} facturas. Los clientes compraron ${n2}. ¿Cuántas facturas quedaron?`,
    operation: '-',
    data1Label: 'Facturas había', data1Unit: 'facturas',
    data2Label: 'Facturas compraron', data2Unit: 'facturas',
    resultLabelTemplate: (res) => `Quedaron ${res} facturas.`,
    icon: '🥐',
  },
  {
    id: 'amigos_fiesta_llegan',
    problemTextTemplate: (n1, n2) => `Ya había ${n1} amigos en la fiesta. Luego llegaron ${n2} amigos más. ¿Cuántos amigos hay en total?`,
    operation: '+',
    data1Label: 'Amigos había', data1Unit: 'amigos',
    data2Label: 'Amigos llegaron', data2Unit: 'amigos',
    resultLabelTemplate: (res) => `Hay ${res} amigos en total en la fiesta.`,
    icon: '🎉',
  },
  {
    id: 'invitados_retiran_temprano',
    problemTextTemplate: (n1, n2) => `A la fiesta llegaron ${n1} invitados. Si ${n2} se retiraron temprano, ¿cuántos invitados quedaron?`,
    operation: '-',
    data1Label: 'Invitados llegaron', data1Unit: 'invitados',
    data2Label: 'Invitados retiraron', data2Unit: 'invitados',
    resultLabelTemplate: (res) => `Quedaron ${res} invitados en la fiesta.`,
    icon: '🥳',
  },
  {
    id: 'tomates_huerta_cosechan',
    problemTextTemplate: (n1, n2) => `Se cosecharon ${n1} tomates rojos y ${n2} tomates verdes de la huerta. ¿Cuántos tomates se cosecharon?`,
    operation: '+',
    data1Label: 'Tomates rojos', data1Unit: 'tomates',
    data2Label: 'Tomates verdes', data2Unit: 'tomates',
    resultLabelTemplate: (res) => `Se cosecharon ${res} tomates en total.`,
    icon: '🍅',
  },
  {
    id: 'zanahorias_conejo_come',
    problemTextTemplate: (n1, n2) => `Un conejo tenía ${n1} zanahorias. Se comió ${n2}. ¿Cuántas zanahorias le quedan?`,
    operation: '-',
    data1Label: 'Zanahorias tenía', data1Unit: 'zanahorias',
    data2Label: 'Zanahorias comió', data2Unit: 'zanahorias',
    resultLabelTemplate: (res) => `Al conejo le quedan ${res} zanahorias.`,
    icon: '🥕',
  },
  {
    id: 'estudiantes_biblioteca_entran',
    problemTextTemplate: (n1, n2) => `En la biblioteca había ${n1} estudiantes leyendo. Entraron ${n2} estudiantes más. ¿Cuántos hay ahora?`,
    operation: '+',
    data1Label: 'Estudiantes había', data1Unit: 'estudiantes',
    data2Label: 'Estudiantes entraron', data2Unit: 'estudiantes',
    resultLabelTemplate: (res) => `Ahora hay ${res} estudiantes en la biblioteca.`,
    icon: '🧑‍🎓',
  },
  {
    id: 'sillas_comedor_ocupan',
    problemTextTemplate: (n1, n2) => `Un comedor tiene ${n1} sillas. Si se ocuparon ${n2} sillas, ¿cuántas quedaron libres?`,
    operation: '-',
    data1Label: 'Sillas total', data1Unit: 'sillas',
    data2Label: 'Sillas ocupadas', data2Unit: 'sillas',
    resultLabelTemplate: (res) => `Quedaron ${res} sillas libres.`,
    icon: '🍽️',
  },
  {
    id: 'collares_hace_vende',
    problemTextTemplate: (n1, n2) => `Ana hizo ${n1} collares. Si vendió ${n2} collares en la feria, ¿cuántos le quedan?`,
    operation: '-',
    data1Label: 'Collares hizo', data1Unit: 'collares',
    data2Label: 'Collares vendió', data2Unit: 'collares',
    resultLabelTemplate: (res) => `A Ana le quedan ${res} collares.`,
    icon: '💎',
  },
  {
    id: 'pelotas_cancha_traen',
    problemTextTemplate: (n1, n2) => `Para jugar había ${n1} pelotas. El profesor trajo ${n2} pelotas más. ¿Cuántas pelotas hay ahora?`,
    operation: '+',
    data1Label: 'Pelotas había', data1Unit: 'pelotas',
    data2Label: 'Pelotas trajo', data2Unit: 'pelotas',
    resultLabelTemplate: (res) => `Ahora hay ${res} pelotas para jugar.`,
    icon: '🏀',
  },
  {
    id: 'vasos_agua_dia',
    problemTextTemplate: (n1, n2) => `Tomé ${n1} vasos de agua por la mañana y ${n2} por la tarde. ¿Cuántos vasos de agua tomé en el día?`,
    operation: '+',
    data1Label: 'Vasos mañana', data1Unit: 'vasos',
    data2Label: 'Vasos tarde', data2Unit: 'vasos',
    resultLabelTemplate: (res) => `Tomé ${res} vasos de agua en el día.`,
    icon: '💧',
  },
  {
    id: 'mensajes_celular_borra',
    problemTextTemplate: (n1, n2) => `Tenías ${n1} mensajes en tu celular. Borraste ${n2} mensajes viejos. ¿Cuántos mensajes te quedan?`,
    operation: '-',
    data1Label: 'Mensajes tenías', data1Unit: 'mensajes',
    data2Label: 'Mensajes borraste', data2Unit: 'mensajes',
    resultLabelTemplate: (res) => `Te quedan ${res} mensajes en el celular.`,
    icon: '📱',
  },
  {
    id: 'fotos_camara_saca',
    problemTextTemplate: (n1, n2) => `Con mi cámara saqué ${n1} fotos del paisaje y ${n2} fotos de animales. ¿Cuántas fotos saqué en total?`,
    operation: '+',
    data1Label: 'Fotos paisaje', data1Unit: 'fotos',
    data2Label: 'Fotos animales', data2Unit: 'fotos',
    resultLabelTemplate: (res) => `Saqué ${res} fotos en total.`,
    icon: '🏞️',
  },
  {
    id: 'abejas_panal_salen',
    problemTextTemplate: (n1, n2) => `En un panal había ${n1} abejas. Salieron ${n2} abejas a buscar polen. ¿Cuántas quedaron en el panal?`,
    operation: '-',
    data1Label: 'Abejas había', data1Unit: 'abejas',
    data2Label: 'Abejas salieron', data2Unit: 'abejas',
    resultLabelTemplate: (res) => `Quedaron ${res} abejas en el panal.`,
    icon: '🐝',
  },
  {
    id: 'barriletes_cielo_vuelan',
    problemTextTemplate: (n1, n2) => `En el cielo volaban ${n1} barriletes rojos. Se sumaron ${n2} barriletes azules. ¿Cuántos barriletes vuelan ahora?`,
    operation: '+',
    data1Label: 'Barriletes rojos', data1Unit: 'barriletes',
    data2Label: 'Barriletes azules', data2Unit: 'barriletes',
    resultLabelTemplate: (res) => `Ahora vuelan ${res} barriletes.`,
    icon: '🪁',
  },
  {
    id: 'hojas_arbol_caen_otono',
    problemTextTemplate: (n1, n2) => `Un árbol tenía ${n1} hojas. En otoño se cayeron ${n2} hojas. ¿Cuántas hojas le quedaron aproximadamente?`,
    operation: '-',
    data1Label: 'Hojas tenía', data1Unit: 'hojas',
    data2Label: 'Hojas cayeron', data2Unit: 'hojas',
    resultLabelTemplate: (res) => `Al árbol le quedaron ${res} hojas aproximadamente.`,
    icon: '🍂',
  },
  {
    id: 'km_viaje_familia',
    problemTextTemplate: (n1, n2) => `Una familia viajó ${n1} km el primer día y ${n2} km el segundo día. ¿Cuántos km viajó en total?`,
    operation: '+',
    data1Label: 'Km día 1', data1Unit: 'km',
    data2Label: 'Km día 2', data2Unit: 'km',
    resultLabelTemplate: (res) => `La familia viajó ${res} km en total.`,
    icon: '🗺️',
  },
  {
    id: 'dinero_ahorrado_gasta_libro',
    problemTextTemplate: (n1, n2) => `Tenías ${n1} pesos ahorrados. Gastaste ${n2} pesos en un libro. ¿Cuánto dinero te queda?`,
    operation: '-',
    data1Label: 'Dinero ahorrado', data1Unit: 'pesos',
    data2Label: 'Dinero gastado', data2Unit: 'pesos',
    resultLabelTemplate: (res) => `Te quedan ${res} pesos.`,
    icon: '💸',
  },
  {
    id: 'manzanas_cosecha_vende',
    problemTextTemplate: (n1, n2) => `Se cosecharon ${n1} manzanas. Si se vendieron ${n2} manzanas, ¿cuántas quedaron sin vender?`,
    operation: '-',
    data1Label: 'Manzanas cosechadas', data1Unit: 'manzanas',
    data2Label: 'Manzanas vendidas', data2Unit: 'manzanas',
    resultLabelTemplate: (res) => `Quedaron ${res} manzanas sin vender.`,
    icon: '🍏',
  },
];


const technologyScenarios: Scenario[] = [
  {
    id: 'archivos_descargados',
    problemTextTemplate: (n1, n2) => `Descargaste ${n1} canciones y ${n2} videos. ¿Cuántos archivos descargaste en total?`,
    operation: '+',
    data1Label: 'Canciones', data1Unit: 'archivos',
    data2Label: 'Videos', data2Unit: 'archivos',
    resultLabelTemplate: (res) => `Descargaste ${res} archivos en total.`,
    icon: '💻',
  },
  {
    id: 'bateria_celular',
    problemTextTemplate: (n1, n2) => `Tu celular tenía ${n1}% de batería y gastaste ${n2}% jugando. ¿Cuánta batería le queda?`,
    operation: '-',
    data1Label: 'Batería inicial', data1Unit: '%',
    data2Label: 'Batería gastada', data2Unit: '%',
    resultLabelTemplate: (res) => `Le queda ${res}% de batería.`,
    icon: '🔋',
  },
  {
    id: 'fotos_tomadas_borradas',
    problemTextTemplate: (n1, n2) => `Tomaste ${n1} fotos con tu tablet. Luego borraste ${n2} que no te gustaron. ¿Cuántas fotos te quedaron?`,
    operation: '-',
    data1Label: 'Fotos tomadas', data1Unit: 'fotos',
    data2Label: 'Fotos borradas', data2Unit: 'fotos',
    resultLabelTemplate: (res) => `Te quedaron ${res} fotos.`,
    icon: '📸',
  },
  {
    id: 'mensajes_recibidos_enviados',
    problemTextTemplate: (n1, n2) => `Recibiste ${n1} mensajes de WhatsApp y enviaste ${n2}. ¿Cuántos mensajes intercambiaste en total?`,
    operation: '+',
    data1Label: 'Mensajes recibidos', data1Unit: 'mensajes',
    data2Label: 'Mensajes enviados', data2Unit: 'mensajes',
    resultLabelTemplate: (res) => `Intercambiaste ${res} mensajes en total.`,
    icon: '💬',
  },
];

const houseScenarios: Scenario[] = [
  {
    id: 'platos_lavar_fregar',
    problemTextTemplate: (n1, n2) => `Había ${n1} platos sucios en la pileta. Mamá lavó ${n2} platos. ¿Cuántos platos sucios quedan?`,
    operation: '-',
    data1Label: 'Platos sucios', data1Unit: 'platos',
    data2Label: 'Platos lavados', data2Unit: 'platos',
    resultLabelTemplate: (res) => `Quedan ${res} platos sucios.`,
    icon: '🍽️',
  },
  {
    id: 'juguetes_ordenar_guardar',
    problemTextTemplate: (n1, n2) => `Había ${n1} juguetes desparramados. Guardaste ${n2} en la caja. ¿Cuántos juguetes más necesitas guardar?`,
    operation: '-',
    data1Label: 'Juguetes desparramados', data1Unit: 'juguetes',
    data2Label: 'Juguetes guardados', data2Unit: 'juguetes',
    resultLabelTemplate: (res) => `Necesitas guardar ${res} juguetes más.`,
    icon: '🧸',
  },
  {
    id: 'libros_estanteria_colocar',
    problemTextTemplate: (n1, n2) => `Tienes ${n1} libros en tu escritorio y ${n2} libros en una pila. ¿Cuántos libros tienes que colocar en la estantería en total?`,
    operation: '+',
    data1Label: 'Libros escritorio', data1Unit: 'libros',
    data2Label: 'Libros pila', data2Unit: 'libros',
    resultLabelTemplate: (res) => `Tienes que colocar ${res} libros en total.`,
    icon: '📚',
  },
  {
    id: 'ropa_lavar_secada',
    problemTextTemplate: (n1, n2) => `Pusiste ${n1} prendas de ropa a lavar. Ya se secaron ${n2} prendas. ¿Cuántas prendas faltan por secarse?`,
    operation: '-',
    data1Label: 'Prendas a lavar', data1Unit: 'prendas',
    data2Label: 'Prendas secas', data2Unit: 'prendas',
    resultLabelTemplate: (res) => `Faltan ${res} prendas por secarse.`,
    icon: '🧺',
  },
];

const transportScenarios: Scenario[] = [
  {
    id: 'kilometros_viaje_auto',
    problemTextTemplate: (n1, n2) => `Un auto recorrió ${n1} kilómetros por la mañana y ${n2} kilómetros por la tarde. ¿Cuántos kilómetros recorrió en total?`,
    operation: '+',
    data1Label: 'Km mañana', data1Unit: 'km',
    data2Label: 'Km tarde', data2Unit: 'km',
    resultLabelTemplate: (res) => `El auto recorrió ${res} km en total.`,
    icon: '🚗',
  },
  {
    id: 'pasajeros_avion_destino',
    problemTextTemplate: (n1, n2) => `Un avión despegó con ${n1} pasajeros. En la primera escala bajaron ${n2} pasajeros. ¿Cuántos pasajeros siguieron viaje?`,
    operation: '-',
    data1Label: 'Pasajeros al despegar', data1Unit: 'pasajeros',
    data2Label: 'Pasajeros bajaron', data2Unit: 'pasajeros',
    resultLabelTemplate: (res) => `Siguieron viaje ${res} pasajeros.`,
    icon: '✈️',
  },
  {
    id: 'bicicletas_parque_suman',
    problemTextTemplate: (n1, n2) => `Había ${n1} bicicletas en el bicicletero del parque. Llegaron ${n2} ciclistas más. ¿Cuántas bicicletas hay ahora?`,
    operation: '+',
    data1Label: 'Bicicletas había', data1Unit: 'bicicletas',
    data2Label: 'Bicicletas llegaron', data2Unit: 'bicicletas',
    resultLabelTemplate: (res) => `Ahora hay ${res} bicicletas.`,
    icon: '🚲',
  },
  {
    id: 'barcos_puerto_zarpan',
    problemTextTemplate: (n1, n2) => `En el puerto había ${n1} barcos amarrados. Zarparon ${n2} barcos. ¿Cuántos barcos quedaron en el puerto?`,
    operation: '-',
    data1Label: 'Barcos había', data1Unit: 'barcos',
    data2Label: 'Barcos zarparon', data2Unit: 'barcos',
    resultLabelTemplate: (res) => `Quedaron ${res} barcos en el puerto.`,
    icon: '🚢',
  },
];

const videogameScenarios: Scenario[] = [
  {
    id: 'monedas_recolectadas_juego',
    problemTextTemplate: (n1, n2) => `En un nivel de tu juego favorito recolectaste ${n1} monedas de oro y ${n2} monedas de plata. ¿Cuántas monedas recolectaste en total?`,
    operation: '+',
    data1Label: 'Monedas de oro', data1Unit: 'monedas',
    data2Label: 'Monedas de plata', data2Unit: 'monedas',
    resultLabelTemplate: (res) => `Recolectaste ${res} monedas en total.`,
    icon: '🪙',
  },
  {
    id: 'vidas_perdidas_juego',
    problemTextTemplate: (n1, n2) => `Empezaste el juego con ${n1} vidas. Perdiste ${n2} vidas al caer en una trampa. ¿Cuántas vidas te quedan?`,
    operation: '-',
    data1Label: 'Vidas iniciales', data1Unit: 'vidas',
    data2Label: 'Vidas perdidas', data2Unit: 'vidas',
    resultLabelTemplate: (res) => `Te quedan ${res} vidas.`,
    icon: '❤️',
  },
  {
    id: 'puntos_experiencia_ganados',
    problemTextTemplate: (n1, n2) => `Ganaste ${n1} puntos de experiencia por completar una misión y ${n2} puntos por derrotar a un enemigo. ¿Cuántos puntos de experiencia ganaste en total?`,
    operation: '+',
    data1Label: 'Puntos misión', data1Unit: 'puntos',
    data2Label: 'Puntos enemigo', data2Unit: 'puntos',
    resultLabelTemplate: (res) => `Ganaste ${res} puntos de experiencia en total.`,
    icon: '🌟',
  },
  {
    id: 'pociones_usadas_juego',
    problemTextTemplate: (n1, n2) => `Tenías ${n1} pociones de curación en tu inventario. Usaste ${n2} pociones después de una batalla. ¿Cuántas pociones te quedan?`,
    operation: '-',
    data1Label: 'Pociones tenías', data1Unit: 'pociones',
    data2Label: 'Pociones usadas', data2Unit: 'pociones',
    resultLabelTemplate: (res) => `Te quedan ${res} pociones.`,
    icon: '🧪',
  },
];

const foodScenarios: Scenario[] = [
  {
    id: 'frutas_ensalada',
    problemTextTemplate: (n1, n2) => `Para una ensalada de frutas, usaste ${n1} manzanas y ${n2} bananas. ¿Cuántas frutas usaste en total?`,
    operation: '+',
    data1Label: 'Manzanas', data1Unit: 'frutas',
    data2Label: 'Bananas', data2Unit: 'frutas',
    resultLabelTemplate: (res) => `Usaste ${res} frutas en total.`,
    icon: '🥗',
  },
  {
    id: 'empanadas_comidas_cena',
    problemTextTemplate: (n1, n2) => `Había ${n1} empanadas para la cena. Entre todos comieron ${n2} empanadas. ¿Cuántas empanadas sobraron?`,
    operation: '-',
    data1Label: 'Empanadas había', data1Unit: 'empanadas',
    data2Label: 'Empanadas comidas', data2Unit: 'empanadas',
    resultLabelTemplate: (res) => `Sobraron ${res} empanadas.`,
    icon: '🥟',
  },
  {
    id: 'chocolates_caja_regalo',
    problemTextTemplate: (n1, n2) => `Una caja de chocolates tiene ${n1} chocolates con leche y ${n2} chocolates amargos. ¿Cuántos chocolates hay en la caja?`,
    operation: '+',
    data1Label: 'Chocolates con leche', data1Unit: 'chocolates',
    data2Label: 'Chocolates amargos', data2Unit: 'chocolates',
    resultLabelTemplate: (res) => `Hay ${res} chocolates en la caja.`,
    icon: '🍫',
  },
  {
    id: 'pizzas_porciones_restantes',
    problemTextTemplate: (n1, n2) => `Una pizza grande tenía ${n1} porciones. Te comiste ${n2} porciones. ¿Cuántas porciones de pizza quedan?`,
    operation: '-',
    data1Label: 'Porciones había', data1Unit: 'porciones',
    data2Label: 'Porciones comidas', data2Unit: 'porciones',
    resultLabelTemplate: (res) => `Quedan ${res} porciones de pizza.`,
    icon: '🍕',
  },
];

const mixedOperationsAdvancedScenarios: Scenario[] = [
  {
    id: 'cajas_lapices',
    problemTextTemplate: (n1, n2) => `Hay ${n1} cajas con ${n2} lápices cada una. ¿Cuántos lápices hay en total?`,
    operation: '*',
    data1Label: 'Cajas', data1Unit: 'cajas',
    data2Label: 'Lápices por caja', data2Unit: 'lápices',
    resultLabelTemplate: (res) => `Hay ${res} lápices en total.`,
    icon: '✏️',
  },
  {
    id: 'flores_floreros',
    problemTextTemplate: (n1, n2) => `Si tienes ${n1} flores y quieres poner ${n2} flores en cada florero, ¿cuántos floreros necesitarás?`,
    operation: '/',
    data1Label: 'Total flores', data1Unit: 'flores',
    data2Label: 'Flores por florero', data2Unit: 'flores',
    resultLabelTemplate: (res) => `Necesitarás ${res} floreros.`,
    icon: '💐',
  },
  {
    id: 'paquetes_galletas_total',
    problemTextTemplate: (n1, n2) => `Compraste ${n1} paquetes de galletas, y cada paquete trae ${n2} galletas. ¿Cuántas galletas compraste en total?`,
    operation: '*',
    data1Label: 'Paquetes', data1Unit: 'paquetes',
    data2Label: 'Galletas por paquete', data2Unit: 'galletas',
    resultLabelTemplate: (res) => `Compraste ${res} galletas en total.`,
    icon: '🍪',
  },
  {
    id: 'caramelos_repartir_niños',
    problemTextTemplate: (n1, n2) => `Tienes ${n1} caramelos y los quieres repartir en partes iguales entre ${n2} niños. ¿Cuántos caramelos le tocarán a cada niño?`,
    operation: '/',
    data1Label: 'Total caramelos', data1Unit: 'caramelos',
    data2Label: 'Niños', data2Unit: 'niños',
    resultLabelTemplate: (res) => `A cada niño le tocarán ${res} caramelos.`,
    icon: '🍬',
  },
];

export const scenarioCollections = {
  [ScenarioSetId.GENERAL]: generalScenarios,
  [ScenarioSetId.TECHNOLOGY]: technologyScenarios,
  [ScenarioSetId.HOUSE]: houseScenarios,
  [ScenarioSetId.TRANSPORT]: transportScenarios,
  [ScenarioSetId.VIDEOGAMES]: videogameScenarios,
  [ScenarioSetId.FOOD]: foodScenarios,
  [ScenarioSetId.MIXED_OPERATIONS_ADVANCED]: mixedOperationsAdvancedScenarios,
  [ScenarioSetId.FIRST_GRADE_ADD_SUB_EASY]: firstGradeEasyAddSubScenarios, // New
  [ScenarioSetId.FIRST_GRADE_ADD_SUB_LT100_SIMPLE]: firstGradeTensSimpleTwoDigitScenarios, // New
};

// Function to generate numbers for a problem based on range and operation
export const generateProblemNumbers = (range: [number, number], operation: '+' | '-' | '*' | '/'): { num1: number, num2: number } => {
  let num1 = getRandomInt(range[0], range[1]);
  let num2 = getRandomInt(range[0], range[1]);

  if (operation === '-') {
    if (num1 < num2) { // Ensure num1 is greater or equal for subtraction
      [num1, num2] = [num2, num1];
    }
  } else if (operation === '/') {
    const minDivisor = Math.max(1, range[0] === 0 && range[1] >=1 ? 1 : range[0]); // Ensure divisor is at least 1 if range allows 0
    num2 = getRandomInt(minDivisor, range[1]);
    if (num2 === 0) num2 = 1; // Absolute fallback for divisor

    // Determine a suitable quotient range
    // Max quotient such that quotient * num2 <= range[1]
    const maxQuotient = Math.floor(range[1] / num2);
    // Min quotient such that quotient * num2 >= range[0]
    // If range[0] is 0, quotient can be 0. Otherwise, quotient should be at least 1.
    let minQuotient = (range[0] === 0 && num2 !== 0) ? 0 : Math.ceil(range[0] / num2);
    
    // Ensure quotient is at least 1 if maxQuotient allows, unless dividend must be 0
    if (maxQuotient > 0) {
      minQuotient = Math.max(1, minQuotient);
    } else if (range[0] > 0 && maxQuotient === 0) { 
      // This case means num2 is too large for the range to have a quotient >= 1
      // that results in a dividend within range.
      // Fallback: try to make quotient 1 if possible, or handle as an edge case.
      // Forcing num1 = num2 if num2 is in range.
      if (num2 >= range[0] && num2 <= range[1]) {
          num1 = num2; // quotient = 1
          return { num1, num2 };
      } else {
          // Fallback to a simpler division or re-generate num2 with tighter constraints
          // For now, let's try to make a simple division if the range is very restrictive
          num1 = num2; // This might be out of range, but it's a fallback.
          return { num1, num2 };
      }
    } else if (maxQuotient === 0 && minQuotient === 0) { // Only possible if range[0] is 0
        // num1 will be 0
    }


    if (maxQuotient < minQuotient) {
      // If still no valid quotient range (e.g. range [1,5], num2 = 6 -> maxQ=0, minQ_sys=1 -> minQ=1)
      // This indicates a difficult pairing. Fallback to num1 = num2 for quotient 1 if num2 is in range.
      if (num2 >= range[0] && num2 <= range[1]) {
        num1 = num2;
      } else if (range[0] === 0) {
        num1 = 0; // If num2 is out of range but 0 is allowed
      } else {
        // Last resort: make num1 a multiple of num2 that's close to range[0] or just num2
        num1 = Math.max(range[0], num2); 
        num1 = Math.ceil(num1 / num2) * num2; 
        if (num1 > range[1]) num1 = num2; // if still too big, just use num2
      }
    } else {
      const quotient = getRandomInt(minQuotient, maxQuotient);
      num1 = quotient * num2;
    }
  } else if (operation === '*') {
     // For multiplication, ensure operands are not excessively large if range is wide,
     // to keep product manageable for the grade level.
     // Example: if range is [0, 999], and we want product not to exceed ~10000 for 3rd grade
     if (range[1] > 100) { // If dealing with potentially large numbers
         if (num1 * num2 > 20000 && num1 > 10 && num2 > 10) { // Heuristic: if product is too big
            // Try to reduce one of the operands
            if (num1 > num2) {
                num1 = getRandomInt(Math.max(1, range[0]), Math.min(range[1], Math.floor(20000 / Math.max(1,num2)), 100));
            } else {
                num2 = getRandomInt(Math.max(1, range[0]), Math.min(range[1], Math.floor(20000 / Math.max(1,num1)), 100));
            }
         }
     }
  }
  return { num1, num2 };
};
