
import { Exercise, ExerciseComponentType, OriginalIconName } from './types';

// Specific exercises for Third Grade - Medidas (s4)
export const thirdGradeMedidasExercises: Exercise[] = [
    {
      id: 'g3-s4-e1',
      title: '¿Cuántos centímetros son?',
      description: 'Convierte cantidades entre 1 y 10 metros a centímetros.',
      iconName: 'MeasureIcon', // OriginalIconName
      isLocked: false,
      componentType: ExerciseComponentType.CONVERTIR_METROS_A_CM,
      data: { totalStars: 10, minMeters: 1, maxMeters: 10 },
      question: 'Convierte los metros indicados a centímetros:',
      content: 'Ingresa el número de centímetros equivalente a los metros mostrados.',
    },
    {
      id: 'g3-s4-e2',
      title: '¿Qué unidad es: km, m o cm?',
      description: 'Identifica la unidad de longitud más adecuada.',
      iconName: 'MeasureIcon',
      isLocked: false,
      componentType: ExerciseComponentType.IDENTIFICAR_UNIDAD_MEDIDA_GENERICO,
      data: {
        totalStars: 15,
        questionPrompt: "¿Qué unidad usarías para medir:",
        itemChallenges: [ 
          { id: 'lapiz_largo', description: "el largo de un lápiz nuevo", correctUnit: "cm", emoji: "✏️" },
          { id: 'goma_borrar_ancho', description: "el ancho de una goma de borrar", correctUnit: "cm", emoji: "🧼" },
          { id: 'cuaderno_pequeno_grosor', description: "el grosor de un cuaderno pequeño", correctUnit: "cm", emoji: "📓" },
          { id: 'clip_largo', description: "el largo de un clip sujetapapeles", correctUnit: "cm", emoji: "📎" },
          { id: 'llave_largo', description: "el largo de una llave de casa", correctUnit: "cm", emoji: "🔑" },
          { id: 'dedo_indice_ancho', description: "el ancho de tu dedo índice", correctUnit: "cm", emoji: "👆" },
          { id: 'moneda_diametro', description: "el diámetro de una moneda grande", correctUnit: "cm", emoji: "🪙" },
          { id: 'insecto_pequeno_longitud', description: "la longitud de un pequeño escarabajo", correctUnit: "cm", emoji: "🐞" },
          { id: 'semilla_girasol_largo', description: "el largo de una semilla de girasol", correctUnit: "cm", emoji: "🌻" },
          { id: 'telefono_movil_ancho', description: "el ancho de un teléfono móvil", correctUnit: "cm", emoji: "📱" },
          { id: 'cuchara_postre_largo', description: "el largo de una cuchara de postre", correctUnit: "cm", emoji: "🥄" },
          { id: 'puerta_altura', description: "la altura de una puerta estándar", correctUnit: "m", emoji: "🚪" },
          { id: 'ventana_grande_ancho', description: "el ancho de una ventana grande", correctUnit: "m", emoji: "🪟" },
          { id: 'mesa_comedor_largo', description: "el largo de una mesa de comedor familiar", correctUnit: "m", emoji: "🍽️" },
          { id: 'pizarron_ancho', description: "el ancho de un pizarrón de clase", correctUnit: "m", emoji: "🧑‍🏫" },
          { id: 'auto_familiar_largo', description: "el largo de un auto familiar", correctUnit: "m", emoji: "🚗" },
          { id: 'cama_matrimonial_ancho', description: "el ancho de una cama matrimonial", correctUnit: "m", emoji: "🛏️" },
          { id: 'armario_altura', description: "la altura de un armario de dos puertas", correctUnit: "m", emoji: "🚪" }, 
          { id: 'sofa_tres_cuerpos_largo', description: "el largo de un sofá de tres cuerpos", correctUnit: "m", emoji: "🛋️" },
          { id: 'habitacion_principal_ancho', description: "el ancho de una habitación principal", correctUnit: "m", emoji: "🏠" },
          { id: 'piscina_jardin_largo', description: "el largo de una piscina de jardín", correctUnit: "m", emoji: "🏊" },
          { id: 'calle_residencial_ancho', description: "el ancho de una calle residencial", correctUnit: "m", emoji: "🏘️" },
          { id: 'altura_arbol_mediano', description: "la altura de un árbol mediano en un parque", correctUnit: "m", emoji: "🌳" },
          { id: 'poste_luz_altura', description: "la altura de un poste de luz en la calle", correctUnit: "m", emoji: "💡" },
          { id: 'distancia_ciudades_vecinas', description: "la distancia entre dos ciudades vecinas", correctUnit: "km", emoji: "🗺️" },
          { id: 'viaje_avion_corto', description: "un viaje corto en avión a otra provincia", correctUnit: "km", emoji: "✈️" },
          { id: 'rio_importante_longitud', description: "la longitud de un río importante", correctUnit: "km", emoji: "🏞️" },
          { id: 'carretera_nacional_extension', description: "la extensión de una carretera nacional", correctUnit: "km", emoji: "🛣️" },
          { id: 'frontera_pais_pequeno_longitud', description: "la longitud de la frontera de un país pequeño", correctUnit: "km", emoji: "🌍" },
          { id: 'viaje_tren_largo', description: "un viaje largo en tren entre regiones", correctUnit: "km", emoji: "🚆" },
          { id: 'maraton_distancia', description: "la distancia de una maratón oficial", correctUnit: "km", emoji: "🏃" },
          { id: 'ruta_senderismo_montana_larga', description: "una ruta de senderismo muy larga en la montaña", correctUnit: "km", emoji: "🥾" },
          { id: 'costa_maritima_extension', description: "la extensión de la costa marítima de una provincia", correctUnit: "km", emoji: "🌊" },
        ],
        unitOptions: [ 
            { unitId: 'cm', label: 'cm', fullLabel: 'Centímetro' },
            { unitId: 'm', label: 'm', fullLabel: 'Metro' },
            { unitId: 'km', label: 'km', fullLabel: 'Kilómetro' },
        ],
      },
      question: 'Elige la unidad más adecuada para medir:', 
      content: 'Observa el objeto o la distancia y selecciona si es mejor usar kilómetros, metros o centímetros.',
    },
    {
      id: 'g3-s4-e3',
      title: '¿Qué unidad es: kg o g?',
      description: 'Identifica la unidad de masa más adecuada.',
      iconName: 'MeasureIcon',
      isLocked: false,
      componentType: ExerciseComponentType.IDENTIFICAR_UNIDAD_MEDIDA_GENERICO, 
      data: {
        totalStars: 12,
        questionPrompt: "¿Qué unidad es más adecuada para pesar:",
        itemChallenges: [ 
          { id: 'pluma_ave', description: "una pluma de ave", correctUnit: "g", emoji: "🪶" },
          { id: 'clip_papel', description: "un clip sujetapapeles", correctUnit: "g", emoji: "📎" },
          { id: 'hoja_papel', description: "una hoja de papel A4", correctUnit: "g", emoji: "📄" },
          { id: 'moneda_pequena', description: "una moneda de 1 peso", correctUnit: "g", emoji: "🪙" },
          { id: 'fresa_fruta', description: "una fresa", correctUnit: "g", emoji: "🍓" },
          { id: 'anillo_oro', description: "un anillo de oro", correctUnit: "g", emoji: "💍" },
          { id: 'lapiz_comun', description: "un lápiz de grafito", correctUnit: "g", emoji: "✏️" },
          { id: 'goma_borrar_escolar', description: "una goma de borrar escolar", correctUnit: "g", emoji: "🧼" },
          { id: 'mariposa_insecto', description: "una mariposa", correctUnit: "g", emoji: "🦋" },
          { id: 'boton_camisa', description: "un botón de camisa", correctUnit: "g", emoji: "🔘" },
          { id: 'rebanada_pan', description: "una rebanada de pan de molde", correctUnit: "g", emoji: "🍞" },
          { id: 'sobre_carta_vacio', description: "un sobre de carta vacío", correctUnit: "g", emoji: "✉️" },
          { id: 'sandia_entera', description: "una sandía entera", correctUnit: "kg", emoji: "🍉" },
          { id: 'paquete_harina_grande', description: "un paquete grande de harina", correctUnit: "kg", emoji: "🛍️" },
          { id: 'persona_adulta_promedio', description: "una persona adulta promedio", correctUnit: "kg", emoji: "🧍" },
          { id: 'perro_mediano', description: "un perro de tamaño mediano", correctUnit: "kg", emoji: "🐕" },
          { id: 'mochila_libros_llena', description: "una mochila llena de libros", correctUnit: "kg", emoji: "🎒" },
          { id: 'television_mediana', description: "un televisor de tamaño mediano", correctUnit: "kg", emoji: "📺" },
          { id: 'silla_comedor', description: "una silla de comedor", correctUnit: "kg", emoji: "🪑" },
          { id: 'bicicleta_adulto', description: "una bicicleta de adulto", correctUnit: "kg", emoji: "🚲" },
          { id: 'bebe_recien_nacido_grande', description: "un bebé recién nacido grande", correctUnit: "kg", emoji: "👶" },
          { id: 'saco_papas_mediano', description: "un saco mediano de papas", correctUnit: "kg", emoji: "🥔" },
          { id: 'maleta_viaje_llena', description: "una maleta de viaje llena", correctUnit: "kg", emoji: "🧳" },
          { id: 'computadora_escritorio', description: "una computadora de escritorio (solo la torre)", correctUnit: "kg", emoji: "🖥️" },
        ],
        unitOptions: [ 
            { unitId: 'g', label: 'g', fullLabel: 'Gramo' },
            { unitId: 'kg', label: 'kg', fullLabel: 'Kilogramo' },
        ],
      },
      question: '¿Qué unidad es más adecuada para pesar?', 
      content: 'Observa el objeto y selecciona si es mejor usar kilogramos o gramos.',
    },
    {
      id: 'g3-s4-e4',
      title: '¿Qué unidad es: ml o l?',
      description: 'Identifica la unidad de capacidad más adecuada.',
      iconName: 'MeasureIcon',
      isLocked: false,
      componentType: ExerciseComponentType.IDENTIFICAR_UNIDAD_MEDIDA_GENERICO, 
      data: {
        totalStars: 12,
        questionPrompt: "¿Qué unidad es más adecuada para medir la capacidad de:",
        itemChallenges: [ 
          { id: 'cuchara_jarabe', description: "una cucharada de jarabe", correctUnit: "ml", emoji: "🥄" },
          { id: 'gotero_medicina', description: "un gotero de medicina", correctUnit: "ml", emoji: "💧" },
          { id: 'perfume_pequeno', description: "un perfume pequeño", correctUnit: "ml", emoji: "🧴" },
          { id: 'jeringa_inyeccion', description: "una jeringa para inyección", correctUnit: "ml", emoji: "💉" },
          { id: 'tinta_boligrafo', description: "la tinta de un bolígrafo", correctUnit: "ml", emoji: "✒️" },
          { id: 'vasito_yogur', description: "un vasito de yogur individual", correctUnit: "ml", emoji: "🥛" }, 
          { id: 'tubo_pasta_dientes', description: "un tubo de pasta de dientes pequeño", correctUnit: "ml", emoji: "🦷" },
          { id: 'esmalte_unas', description: "un frasco de esmalte de uñas", correctUnit: "ml", emoji: "💅" },
          { id: 'lata_gaseosa_pequena', description: "una lata pequeña de gaseosa", correctUnit: "ml", emoji: "🥤" },
          { id: 'taza_cafe', description: "una taza de café", correctUnit: "ml", emoji: "☕" },
          { id: 'vaso_jugo_pequeno', description: "un vaso de jugo pequeño", correctUnit: "ml", emoji: "🧃" },
          { id: 'biberon_bebe', description: "un biberón para bebé", correctUnit: "ml", emoji: "🍼" },
          { id: 'botella_agua_grande', description: "una botella grande de agua", correctUnit: "l", emoji: "🍾" },
          { id: 'carton_leche', description: "un cartón de leche", correctUnit: "l", emoji: "🥛" },
          { id: 'jarra_jugo_grande', description: "una jarra grande de jugo", correctUnit: "l", emoji: "🍹" },
          { id: 'balde_pintura', description: "un balde de pintura", correctUnit: "l", emoji: "🪣" },
          { id: 'tanque_nafta_auto', description: "el tanque de nafta de un auto", correctUnit: "l", emoji: "⛽" },
          { id: 'pileta_inflable_pequena', description: "una pileta inflable pequeña", correctUnit: "l", emoji: "🏊" },
          { id: 'banera_llena', description: "una bañera llena", correctUnit: "l", emoji: "🛁" },
          { id: 'bidon_aceite_auto', description: "un bidón de aceite para auto", correctUnit: "l", emoji: "🛢️" },
          { id: 'olla_grande_sopa', description: "una olla grande de sopa", correctUnit: "l", emoji: "🍲" },
          { id: 'regadera_plantas', description: "una regadera para plantas", correctUnit: "l", emoji: "🪴" },
          { id: 'lavarropas_agua', description: "el agua que usa un lavarropas", correctUnit: "l", emoji: "🧺" },
          { id: 'acuario_mediano', description: "un acuario mediano", correctUnit: "l", emoji: "🐠" },
        ],
        unitOptions: [ 
            { unitId: 'ml', label: 'ml', fullLabel: 'Mililitro' },
            { unitId: 'l', label: 'l', fullLabel: 'Litro' },
        ],
      },
      question: '¿Qué unidad es más adecuada para medir la capacidad de...?', 
      content: 'Observa el objeto o recipiente y selecciona si es mejor usar mililitros o litros.',
    },
    {
      id: 'g3-s4-e5',
      title: 'Sumar con claves: ¿Cuántos litros caben en los recipientes?',
      description: 'Problemas de capacidad con sumas y restas simples de litros.',
      iconName: 'MeasureIcon',
      isLocked: false,
      componentType: ExerciseComponentType.PROBLEMAS_CAPACIDAD_SUMA_RESTA,
      data: {
        totalStars: 10,
        problems: [
          { id: 'suma_jarra_balde', textTemplate: (n1: number, n2: number) => `En una jarra caben ${n1} ${n1 === 1 ? 'litro' : 'litros'} de agua y en un balde caben ${n2} ${n2 === 1 ? 'litro' : 'litros'}. ¿Cuántos litros caben en total entre los dos recipientes?`, num1Range: [1, 5], num2Range: [1, 10], operation: '+', unit: "litros", resultUnitSingular: "litro", resultUnitPlural: "litros", emoji: "🚰" },
          { id: 'resta_tanque_nafta', textTemplate: (n1: number, n2: number) => `Un tanque tiene ${n1} ${n1 === 1 ? 'litro' : 'litros'} de nafta. Si se usan ${n2} ${n2 === 1 ? 'litro' : 'litros'} para un viaje, ¿cuántos litros quedan en el tanque?`, num1Range: [10, 50], num2Range: [1, 9], operation: '-', unit: "litros", resultUnitSingular: "litro", resultUnitPlural: "litros", emoji: "⛽" },
          { id: 'suma_piscina_llenado', textTemplate: (n1: number, n2: number) => `Para llenar una piscina pequeña se usaron ${n1} ${n1 === 1 ? 'litro' : 'litros'} de una manguera y luego se agregaron ${n2} ${n2 === 1 ? 'litro' : 'litros'} más con baldes. ¿Cuántos litros se usaron en total?`, num1Range: [20, 100], num2Range: [5, 50], operation: '+', unit: "litros", resultUnitSingular: "litro", resultUnitPlural: "litros", emoji: "🏊" },
          { id: 'resta_botella_gaseosa', textTemplate: (n1: number, n2: number) => `Una botella grande de gaseosa tiene ${n1} ${n1 === 1 ? 'litro' : 'litros'}. Si se sirvieron ${n2} ${n2 === 1 ? 'litro' : 'litros'} en una fiesta, ¿cuántos litros de gaseosa quedaron?`, num1Range: [2, 5], num2Range: [1, 2], operation: '-', unit: "litros", resultUnitSingular: "litro", resultUnitPlural: "litros", emoji: "🥤" },
          { id: 'suma_leche_receta', textTemplate: (n1: number, n2: number) => `Para una receta se necesitan ${n1} ${n1 === 1 ? 'litro' : 'litros'} de leche para la masa y ${n2} ${n2 === 1 ? 'litro' : 'litros'} para el relleno. ¿Cuántos litros de leche se necesitan en total?`, num1Range: [1, 3], num2Range: [1, 2], operation: '+', unit: "litros", resultUnitSingular: "litro", resultUnitPlural: "litros", emoji: "🥛" },
          { id: 'resta_agua_regadera', textTemplate: (n1: number, n2: number) => `Una regadera llena contiene ${n1} ${n1 === 1 ? 'litro' : 'litros'} de agua. Después de regar las plantas del balcón, quedan ${n2} ${n2 === 1 ? 'litro' : 'litros'}. ¿Cuántos litros se usaron?`, num1Range: [5, 10], num2Range: [1, 4], operation: '-', unit: "litros", resultUnitSingular: "litro", resultUnitPlural: "litros", emoji: "🪴" }
        ]
      },
      question: 'Resuelve el problema de capacidad:',
      content: 'Lee el problema, realiza la operación y escribe el resultado en litros.',
    },
    {
      id: 'g3-s4-e6',
      title: 'Capacidad Total: Jarras y Vasos (en ml)',
      description: 'Calcula la capacidad total en mililitros combinando jarras y vasos.',
      iconName: 'MeasureIcon',
      isLocked: false,
      componentType: ExerciseComponentType.SUMAR_CAPACIDAD_CONVERSION_ML,
      data: {
        totalStars: 10,
        problems: [
          { id: 'p1_g3s4e6', term1: { itemName: "una jarra grande", litersRange: [1,1], millilitersRange: [500,500] }, term2: { itemName: "2 vasos pequeños", litersRange: [0,0], millilitersRange: [400,400] }, containerName: "la mezcla", emoji: '🥤' },
          { id: 'p2_g3s4e6', term1: { itemName: "una botella", litersRange: [0,0], millilitersRange: [750,750] }, term2: { itemName: "3 vasos medianos", litersRange: [0,0], millilitersRange: [450,450] }, containerName: "un recipiente", emoji: '🫙' },
          { id: 'p3_g3s4e6', term1: { itemName: "un bidón", litersRange: [2,2], millilitersRange: [0,0] }, term2: { itemName: "1 vaso grande", litersRange: [0,0], millilitersRange: [250,250] }, containerName: "el total", emoji: '💧' },
          { id: 'p4_g3s4e6', term1: { itemName: "una jarra", litersRange: [1,1], millilitersRange: [0,0] }, term2: { itemName: "4 vasos chicos", litersRange: [0,0], millilitersRange: [400,400] }, containerName: "la limonada", emoji: '🍹' },
          { id: 'p5_g3s4e6', term1: { itemName: "una botella de jugo", litersRange: [1,1], millilitersRange: [250,250] }, term2: { itemName: "2 vasos de jugo", litersRange: [0,0], millilitersRange: [300,300] }, containerName: "la ponchera", emoji: '🧉' },
        ]
      },
      question: 'Calcula el total en mililitros:',
    },
    {
      id: 'g3-s4-e7',
      title: '¿Qué Hora Es? (Reloj Analógico)',
      description: 'Lee la hora que marca el reloj analógico y selecciona la opción correcta.',
      iconName: 'MeasureIcon',
      isLocked: false,
      componentType: ExerciseComponentType.LEER_RELOJ_OPCIONES,
      data: {
        totalStars: 12,
        times: [
          { hours: 3, minutes: 0, correctText: "Son las tres en punto", distractors: ["Son las tres y media", "Son las doce y tres", "Son las seis y quince"] },
          { hours: 9, minutes: 15, correctText: "Son las nueve y cuarto", distractors: ["Son las nueve y media", "Son las tres menos cuarto", "Son las nueve en punto"] },
          { hours: 6, minutes: 30, correctText: "Son las seis y media", distractors: ["Son las seis en punto", "Son las siete menos cuarto", "Son las doce y media"] },
          { hours: 1, minutes: 45, correctText: "Son las dos menos cuarto", distractors: ["Es la una y cuarenta y cinco", "Son las dos y cuarto", "Es la una y media"] },
          { hours: 11, minutes: 0, correctText: "Son las once en punto", distractors: ["Son las once y cuarto", "Son las diez y media", "Es la una menos once"] },
          { hours: 5, minutes: 15, correctText: "Son las cinco y cuarto", distractors: ["Son las cinco menos cuarto", "Son las seis y cuarto", "Son las cinco y media"] },
          { hours: 10, minutes: 30, correctText: "Son las diez y media", distractors: ["Son las diez y cuarto", "Son las once menos veinte", "Son las diez en punto"] },
          { hours: 7, minutes: 45, correctText: "Son las ocho menos cuarto", distractors: ["Son las siete y cuarenta y cinco", "Son las siete y cuarto", "Son las ocho y media"] },
          { hours: 12, minutes: 0, correctText: "Son las doce en punto", distractors: ["Es mediodía y cuarto", "Son las doce y media", "Faltan doce para la una"] },
          { hours: 4, minutes: 15, correctText: "Son las cuatro y cuarto", distractors: ["Son las cuatro y media", "Son las cinco menos cuarto", "Son las cuatro en punto"] },
          { hours: 8, minutes: 30, correctText: "Son las ocho y media", distractors: ["Son las ocho y cuarto", "Son las nueve menos cuarto", "Son las ocho en punto"] },
          { hours: 2, minutes: 45, correctText: "Son las tres menos cuarto", distractors: ["Son las dos y cuarenta y cinco", "Son las tres y cuarto", "Son las dos y media"] },
        ]
      },
      question: '¿Qué hora marca el reloj?',
    },
    {
      id: 'g3-s4-e8',
      title: 'Suma de Capacidades (con conversión a ml)',
      description: 'Suma dos capacidades, convirtiendo litros a mililitros si es necesario.',
      iconName: 'MeasureIcon',
      isLocked: false,
      componentType: ExerciseComponentType.SUMAR_CAPACIDAD_CONVERSION_ML,
      data: {
        totalStars: 10,
        problems: [
          { id: 'p_conv1', term1: { itemName: "una botella", litersRange: [0, 1], millilitersRange: [250, 750] }, term2: { itemName: "una jarra", litersRange: [0, 2], millilitersRange: [0, 500] }, containerName: "un balde", emoji: '🪣' },
          { id: 'p_conv2', term1: { itemName: "un vaso grande", litersRange: [0, 0], millilitersRange: [300, 600] }, term2: { itemName: "una taza medidora", litersRange: [0, 1], millilitersRange: [50, 450] }, containerName: "una olla", emoji: '🍲' },
          { id: 'p_conv3', term1: { itemName: "un cartón de leche", litersRange: [1, 1], millilitersRange: [0, 0] }, term2: { itemName: "un chorrito de crema", litersRange: [0, 0], millilitersRange: [50, 200] }, containerName: "un tazón", emoji: '🥣' },
          { id: 'p_conv4', term1: { itemName: "una regadera", litersRange: [1, 3], millilitersRange: [0, 0] }, term2: { itemName: "un pulverizador", litersRange: [0, 0], millilitersRange: [200, 800] }, containerName: "un tanque de jardín", emoji: '🪴' },
          { id: 'p_conv5', term1: { itemName: "un bidón", litersRange: [2, 5], millilitersRange: [0, 0] }, term2: { itemName: "otro bidón más pequeño", litersRange: [0, 1], millilitersRange: [500, 900] }, containerName: "un contenedor industrial", emoji: '🛢️' },
        ]
      },
      question: 'Calcula el total en mililitros, convirtiendo si es necesario:',
    },
    {
      id: 'g3-s4-e9',
      title: '¿Las monedas suman $1, más o menos?',
      description: 'Compara el valor de un grupo de monedas con $1.',
      iconName: 'MeasureIcon',
      isLocked: false,
      componentType: ExerciseComponentType.COMPARAR_MONEDAS_CON_PESO,
      data: {
        totalStars: 10,
        coinCollections: [ // value is in cents
          { coins: [{value: 50, count: 1, label: "50c"}, {value: 25, count: 1, label:"25c"}], correctOption: 'less', emoji: '🪙' }, 
          { coins: [{value: 50, count: 2, label: "50c"}], correctOption: 'equal', emoji: '💰' }, 
          { coins: [{value: 25, count: 3, label: "25c"}, {value: 10, count: 2, label:"10c"}, {value:5, count:1, label:"5c"}], correctOption: 'equal', emoji: '🪙' }, 
          { coins: [{value: 50, count: 1, label: "50c"}, {value: 25, count: 2, label:"25c"}, {value:10, count:1, label:"10c"}], correctOption: 'more', emoji: '💰' }, 
          { coins: [{value: 10, count: 8, label: "10c"}], correctOption: 'less', emoji: '🪙' }, 
          { coins: [{value: 25, count: 4, label: "25c"}], correctOption: 'equal', emoji: '💰' }, 
          { coins: [{value: 50, count: 3, label: "50c"}], correctOption: 'more', emoji: '🪙' }, 
          { coins: [{value: 10, count: 9, label: "10c"}, {value: 5, count: 1, label:"5c"}], correctOption: 'less', emoji: '💰' }, 
          { coins: [{value: 1, count: 100, label: "1c"}], correctOption: 'equal', emoji: '🪙' }, 
          { coins: [{value: 25, count: 5, label: "25c"}], correctOption: 'more', emoji: '💰' }, 
        ]
      },
      question: 'El valor total de las monedas es:',
    },
    {
      id: 'g3-s4-e10',
      title: '¿Cuántos pesos hay? ($1 y $2)',
      description: 'Suma el valor de monedas de $1 y $2.',
      iconName: 'MeasureIcon',
      isLocked: false,
      componentType: ExerciseComponentType.SUMAR_ITEMS_MONETARIOS_SIMPLES,
      data: {
        totalStars: 10,
        problems: [ // value is in cents
          { items: [{value: 100, count: 3, label: "$1"}, {value: 200, count: 1, label: "$2"}]}, 
          { items: [{value: 100, count: 5, label: "$1"}, {value: 200, count: 2, label: "$2"}]}, 
          { items: [{value: 100, count: 2, label: "$1"}, {value: 200, count: 3, label: "$2"}]}, 
          { items: [{value: 200, count: 4, label: "$2"}]}, 
          { items: [{value: 100, count: 6, label: "$1"}]}, 
          { items: [{value: 100, count: 4, label: "$1"}, {value: 200, count: 2, label: "$2"}]}, 
          { items: [{value: 100, count: 1, label: "$1"}, {value: 200, count: 5, label: "$2"}]}, 
        ]
      },
      question: '¿Cuántos pesos hay en total?',
    },
    {
      id: 'g3-s4-e11',
      title: '¿Cuántos pesos hay? (50c, $1, $2)',
      description: 'Suma monedas de 50c, $1 y $2. El resultado puede tener centavos.',
      iconName: 'MeasureIcon',
      isLocked: false,
      componentType: ExerciseComponentType.SUMAR_MONEDAS_PESOS_CENTAVOS,
      data: {
        totalStars: 10,
        problems: [ // value is in cents
          { coins: [{value: 50, count: 1, label: "50c"}, {value: 100, count: 1, label: "$1"}]}, 
          { coins: [{value: 50, count: 3, label: "50c"}, {value: 200, count: 1, label: "$2"}]}, 
          { coins: [{value: 50, count: 2, label: "50c"}, {value: 100, count: 2, label: "$1"}, {value: 200, count: 1, label: "$2"}]},
          { coins: [{value: 50, count: 1, label: "50c"}, {value: 200, count: 2, label: "$2"}]}, 
          { coins: [{value: 50, count: 5, label: "50c"}, {value: 100, count: 1, label: "$1"}]}, 
        ]
      },
      question: '¿Cuántos pesos hay en total? (Ej: $3.50)',
    },
    {
      id: 'g3-s4-e12',
      title: '¿Cuántos pesos hay? (Billetes hasta $50)',
      description: 'Suma el valor de billetes de $10, $20 y $50.',
      iconName: 'MeasureIcon',
      isLocked: false,
      componentType: ExerciseComponentType.SUMAR_ITEMS_MONETARIOS_SIMPLES,
      data: {
        totalStars: 10,
        problems: [ // value is in cents
          { items: [{value: 1000, count: 2, label: "$10"}, {value: 2000, count: 1, label: "$20"}]}, 
          { items: [{value: 1000, count: 1, label: "$10"}, {value: 5000, count: 1, label: "$50"}]}, 
          { items: [{value: 2000, count: 2, label: "$20"}, {value: 1000, count: 1, label: "$10"}]}, 
          { items: [{value: 5000, count: 1, label: "$50"}, {value: 2000, count: 2, label: "$20"}, {value: 1000, count: 1, label: "$10"}]},
          { items: [{value: 1000, count: 3, label: "$10"}, {value: 5000, count: 1, label: "$50"}]}, 
        ]
      },
      question: '¿Cuántos pesos suman los billetes?',
    },
];
