
import { Exercise, ExerciseComponentType, OriginalIconName } from './types';

// Specific exercises for Third Grade - Numeros (s1)
export const thirdGradeNumerosExercises: Exercise[] = [
  { id: 'g3-s1-e1', title: 'Escribir hasta 10.000.', description: 'Escribe el número que se muestra en palabras.', iconName: 'BookOpenIcon', isLocked: false, componentType: ExerciseComponentType.ESCRIBIR_HASTA_10000, data: { totalStars: 10, minNumber: 1000, maxNumber: 10000 }, question: '¿Qué número hay escrito?', content: 'Observa el número escrito en palabras e ingrésalo.' },
  { id: 'g3-s1-e2', title: 'Comparar hasta 10.000.', description: 'Elige el símbolo correcto (<, =, >) para comparar los números.', iconName: 'BookOpenIcon', isLocked: false, componentType: ExerciseComponentType.COMPARAR_HASTA_10000, data: { totalStars: 10, minNumber: 100, maxNumber: 10000 }, question: 'Compara los números. ¿Cuál es el símbolo correcto?', content: 'Observa los dos números y elige el símbolo que los compara correctamente.' },
  { id: 'g3-s1-e3', title: 'Componer hasta 10.000. Con ábaco.', description: 'Representa el número indicado en el ábaco interactivo.', iconName: 'OwlIcon', isLocked: false, componentType: ExerciseComponentType.COMPONER_HASTA_10000_ABACO, data: { totalStars: 8, minNumber: 1, maxNumber: 9999 }, question: 'Representa el siguiente número en el ábaco:', content: 'Usa el ábaco para formar el número que se muestra.' },
  { id: 'g3-s1-e4', title: 'Componer hasta 10.000. Con texto.', description: 'Descompón números usando texto indicando UM, C, D y U.', iconName: 'NumbersIcon', isLocked: false, componentType: ExerciseComponentType.COMPONER_HASTA_10000_TEXTO, data: { totalStars: 10, minNumber: 1, maxNumber: 9999 }, question: 'Descompón el número en Unidades de Millar, Centenas, Decenas y Unidades:', content: 'Introduce cuántas UM, C, D y U tiene el número.' },
  { id: 'g3-s1-e5', title: 'Aproximar números a decenas.', description: 'Redondea a la decena más próxima.', iconName: 'BookOpenIcon', isLocked: false, componentType: ExerciseComponentType.APROXIMAR_NUMERO, data: { totalStars: 10, minNumber: 10, maxNumber: 999, roundingUnit: 10 }, question: 'Redondea el número a la decena más próxima:', content: 'Practica el redondeo de números a la decena más cercana.' },
  { id: 'g3-s1-e6', title: 'Aproximar números a centenas.', description: 'Redondea a la centena más próxima.', iconName: 'BookOpenIcon', isLocked: false, componentType: ExerciseComponentType.APROXIMAR_NUMERO, data: { totalStars: 10, minNumber: 100, maxNumber: 9999, roundingUnit: 100 }, question: 'Redondea el número a la centena más próxima:', content: 'Practica el redondeo de números a la centena más cercana.' },
  { id: 'g3-s1-e7', title: 'Aproximar números a millares.', description: 'Redondea al millar más próximo.', iconName: 'BookOpenIcon', isLocked: false, componentType: ExerciseComponentType.APROXIMAR_NUMERO, data: { totalStars: 10, minNumber: 1000, maxNumber: 9999, roundingUnit: 1000 }, question: 'Redondea el número al millar más próximo:', content: 'Practica el redondeo de números al millar más cercano.' },
  { id: 'g3-s1-e8', title: 'Identificar ordinales hasta el 20.', description: 'Reconoce números ordinales y su valor.', iconName: 'BookOpenIcon', isLocked: false, componentType: ExerciseComponentType.IDENTIFICAR_ORDINALES, data: { totalStars: 10, minCardinal: 1, maxCardinal: 20 }, question: 'Identifica el número ordinal:', content: 'Selecciona el número cardinal que corresponde al ordinal mostrado.' },
  { id: 'g3-s1-e9', title: 'Identificar ordinales (21º a 100º).', description: 'Reconoce ordinales desde Vigésimo primero hasta Centésimo.', iconName: 'BookOpenIcon', isLocked: false, componentType: ExerciseComponentType.IDENTIFICAR_ORDINALES, data: { totalStars: 10, minCardinal: 21, maxCardinal: 100 }, question: 'Identifica el número ordinal correspondiente:', content: 'Selecciona el cardinal para ordinales entre el 21º y el 100º.' },
  { id: 'g3-s1-e10', title: 'Sumar números de 2 cifras.', description: 'Practica la suma de números de dos cifras.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.ARITMETICA_SIMPLE_2_CIFRAS, data: { totalStars: 10, minOperand: 10, maxOperand: 99, operationType: 'addition' }, question: 'Resuelve la suma:', content: 'Realiza la suma de los dos números de dos cifras.' },
  { id: 'g3-s1-e11', title: 'Restar números de 2 cifras.', description: 'Practica la resta de números de dos cifras.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.ARITMETICA_SIMPLE_2_CIFRAS, data: { totalStars: 10, minOperand: 10, maxOperand: 99, operationType: 'subtraction' }, question: 'Resuelve la resta:', content: 'Realiza la resta de los dos números de dos cifras (el resultado será positivo o cero).' },
  { id: 'g3-s1-e12', title: 'Sumar y restar números de 2 cifras.', description: 'Practica sumas y restas con números de dos cifras.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.ARITMETICA_SIMPLE_2_CIFRAS, data: { totalStars: 10, minOperand: 10, maxOperand: 99, operationType: 'mixed' }, question: 'Resuelve la operación:', content: 'Realiza la suma o resta de los dos números de dos cifras.' },
  { id: 'g3-s1-e13', title: 'Cálculo mental: sumar números de 3 cifras.', description: 'Resuelve sumas de tres cifras mentalmente.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'addition', minOperand: 100, maxOperand: 999 }, question: 'Calcula mentalmente.', content: 'Realiza la suma mentalmente.' },
  { id: 'g3-s1-e14', title: 'Cálculo mental: restar números de 3 cifras.', description: 'Realiza restas de tres cifras sin ayuda de papel.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'subtraction_3_digit', minOperand: 100, maxOperand: 999 }, question: 'Calcula mentalmente la resta:', content: 'Practica la resta mental con números de tres cifras.' },
  { id: 'g3-s1-e15', title: 'Cálculo mental: sumar y restar números de 3 cifras.', description: 'Alterna entre sumas y restas mentales con números de tres cifras.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'mixed_addition_subtraction_3_digit', minOperand: 100, maxOperand: 999 }, question: 'Calcula mentalmente la operación:', content: 'Practica sumas y restas mentales con números de tres cifras.' },
  { id: 'g3-s1-e16', title: 'Cálcular el doble (hasta 50).', description: 'Encuentra el doble de números hasta el 50.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'double', minOperand: 1, maxOperand: 50 }, question: 'Calcula el doble:', content: 'Encuentra el doble del número que se muestra.' },
  { id: 'g3-s1-e17', title: 'Cálcular la mitad (< 50).', description: 'Encuentra la mitad de números pares inferiores a 50.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'half', minOperand: 2, maxOperand: 48 }, question: 'Calcula la mitad:', content: 'Encuentra la mitad del número par que se muestra.' },
  { id: 'g3-s1-e18', title: 'Cálcular el triple (hasta 50).', description: 'Encuentra el triple de números hasta el 50.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'triple', minOperand: 1, maxOperand: 50 }, question: 'Calcula el triple:', content: 'Encuentra el triple del número que se muestra.' },
  { id: 'g3-s1-e19', title: 'Cálculo mental: el doble de números hasta el 100.', description: 'Encuentra el doble de números hasta cien.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'double', minOperand: 1, maxOperand: 100 }, question: 'Calcula mentalmente.', content: 'Encuentra el doble del número.' },
  { id: 'g3-s1-e20', title: 'Cálculo mental: la mitad (hasta 100).', description: 'Encuentra la mitad de números pares hasta el 100.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'half', minOperand: 2, maxOperand: 100 }, question: 'Calcula la mitad:', content: 'Practica el cálculo mental de la mitad para números pares hasta 100.' },
  { id: 'g3-s1-e21', title: 'Cálculo mental: el triple (hasta 100).', description: 'Encuentra el triple de números hasta el 100.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'triple', minOperand: 1, maxOperand: 100 }, question: 'Calcula el triple:', content: 'Practica el cálculo mental del triple para números hasta 100.' },
  { id: 'g3-s1-e22', title: 'Cálculo mental: el tercio (hasta 100).', description: 'Encuentra el tercio de números múltiplos de 3 hasta el 100.', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'third', minOperand: 3, maxOperand: 99 }, question: 'Calcula el tercio:', content: 'Practica el cálculo mental del tercio para múltiplos de 3 hasta 99.' },
  { id: 'g3-s1-e23', title: 'Cálculo mental: multiplicar por 10, 100, 1000.', description: 'Multiplica por la unidad seguida de ceros (10, 100, 1000).', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'multiplyByPowerOfTen', minOperand: 1, maxOperand: 999 }, question: 'Calcula mentalmente la multiplicación:', content: 'Multiplica el número por 10, 100 o 1000.' },
  { id: 'g3-s1-e24', title: 'Cálculo mental: dividir por 2, 3, 5 y 10.', description: 'Divide mentalmente entre 2, 3, 5 o 10 (resultados exactos).', iconName: 'OperationsIcon', isLocked: false, componentType: ExerciseComponentType.CALCULA_MENTALMENTE, data: { totalStars: 10, problemType: 'divideByBasicDivisor', minResultOperand: 1, maxResultOperand: 50 }, question: 'Calcula mentalmente la división:', content: 'Divide el número entre 2, 3, 5 o 10. El resultado será exacto.' },
  { 
    id: 'g3-s1-e25', 
    title: 'Fracciones: leer fracciones propias', 
    description: 'Selecciona la forma correcta de leer fracciones propias.', 
    iconName: 'BookOpenIcon', 
    isLocked: false, 
    componentType: ExerciseComponentType.LEER_FRACCIONES_PROPIAS, 
    data: { 
      totalStars: 7, // Number of challenges to complete
      challenges: [
        { numerator: 1, denominator: 2, fractionString: "1 / 2", correctWordsString: "Un medio", options: ["Un medio", "Dos tercios", "Un cuarto", "Un entero"] },
        { numerator: 2, denominator: 3, fractionString: "2 / 3", correctWordsString: "Dos tercios", options: ["Dos tercios", "Un tercio", "Tres medios", "Dos cuartos"] },
        { numerator: 3, denominator: 4, fractionString: "3 / 4", correctWordsString: "Tres cuartos", options: ["Tres cuartos", "Un cuarto", "Cuatro tercios", "Tres quintos"] },
        { numerator: 1, denominator: 5, fractionString: "1 / 5", correctWordsString: "Un quinto", options: ["Un quinto", "Cinco unos", "Un sexto", "Dos quintos"] },
        { numerator: 4, denominator: 7, fractionString: "4 / 7", correctWordsString: "Cuatro séptimos", options: ["Cuatro séptimos", "Siete cuartos", "Cuatro sextos", "Tres séptimos"] },
        { numerator: 5, denominator: 8, fractionString: "5 / 8", correctWordsString: "Cinco octavos", options: ["Cinco octavos", "Ocho quintos", "Cinco novenos", "Seis octavos"] },
        { numerator: 2, denominator: 9, fractionString: "2 / 9", correctWordsString: "Dos novenos", options: ["Dos novenos", "Nueve medios", "Dos décimos", "Tres novenos"] },
        { numerator: 1, denominator: 3, fractionString: "1 / 3", correctWordsString: "Un tercio", options: ["Un tercio", "Tres unos", "Un medio", "Dos tercios"] },
        { numerator: 3, denominator: 5, fractionString: "3 / 5", correctWordsString: "Tres quintos", options: ["Tres quintos", "Cinco tercios", "Tres sextos", "Dos quintos"] },
        { numerator: 1, denominator: 6, fractionString: "1 / 6", correctWordsString: "Un sexto", options: ["Un sexto", "Seis unos", "Un quinto", "Dos sextos"] },
        { numerator: 6, denominator: 7, fractionString: "6 / 7", correctWordsString: "Seis séptimos", options: ["Seis séptimos", "Siete sextos", "Cinco séptimos", "Seis octavos"] }
      ]
    }, 
    question: 'Selecciona cómo se lee la fracción:', 
    content: 'Observa la fracción y elige la opción que indica cómo se lee.' 
  },
  { id: 'g3-s1-e26', title: 'Fracciones: representar fracciones', description: 'Practica cómo representar fracciones visualmente.', iconName: 'BookOpenIcon', isLocked: false, componentType: ExerciseComponentType.REPRESENTAR_FRACCIONES, data: { totalStars: 10, maxDenominator: 8 }, question: 'Representa la fracción:', content: 'Selecciona las partes correctas para representar la fracción indicada.' },
  { id: 'g3-s1-e27', title: 'Fracciones: escribir fracciones propias', description: 'Escribe la fracción que corresponde a la descripción o imagen.', iconName: 'BookOpenIcon', isLocked: false, componentType: ExerciseComponentType.ESCRIBIR_FRACCIONES_PROPIAS, data: { totalStars: 10, maxDenominator: 9 }, question: 'Escribe la fracción que ves:', content: 'Observa la imagen y escribe la fracción correspondiente.' },
];
